SocialiteProviders/Providers

src/Uber/Provider.php
The Uber api does not accept multiple scope to be sent as a string with separators. It must be an array of scopes like: ``scope[0]=profile&scope[1]=history``
=> Fix the Uber provider

src/Dataporten/Provider.php
Default to the authorized scopes for a Dataporten Oauth 2 Client. The default authorized scopes are 'userid' and 'profile'.
=> [Dataporten] Update Provider.php

src/Jira/RsaSha1Signature.php
Without this fix, there is a type error in signature of baseString function:
```
Type error: Argument 1 passed to SocialiteProviders\Jira\RsaSha1Signature::baseString() 
must be an instance of SocialiteProviders\Jira\Url, 
instance of GuzzleHttp\Psr7\Uri given, 
called in src/Jira/RsaSha1Signature.php on line 26
```
=> Fixes a type error in Jira integration

src/Line/Provider.php
Conduct array key check while mapping to object
=> Line API will not return avatar url when user did not set one

src/Slack/Provider.php
The default scopes for the Slack provider are an issue since some combinations are forbidden. Here is what I get when I try to redirect a user with the following code:
```php
Socialite::with('slack')->scopes(['channels:history', 'channels:read', 'users:read', 'emoji:read', 'team:read'])->redirect();
```
The removal of the default scopes is **a breaking changement!** Merge this carefully.
=> Remove Slack's default scopes to avoid conflicts

src/Spotify/Provider.php
fix Spotify user object:
- correct `name` from `$user['id']` to `$user['display_name']`
- correct `nickname` to `null`
- add `profileUrl` value which exists as `$user['href']` for any given Spotify user profile
...as per https://developer.spotify.com/web-api/console/get-users-profile/
=> update Spotify provider mapUserToObject

src/Shopify/Provider.php
The oauth domain is not a constant with shopify - each store hais on its own subdomain.
The current setup of defining a subdomain in the services config array will not work when for example installing an app or sales channel from the Shopify app store. The subdomain value need to be dynamic from the shop GET parameter.
This PR swaps out the current subdomain config item for the shop param in the current request.
I don't think this is the ideal solution, but it works and at least gets the ball rolling to sort out the issue.
I have implemented it to have no breaking changes - if the subdomain is set - that will be used, if not it will fallback to the shop param on the request.
=> Dynamic myshopify.com subdomain

build/split.sh, src/GameWisp/GameWispExtendSocialite.php, src/GameWisp/Provider.php, src/GameWisp/composer.json
Added support for GameWisp. A fan funding service for livestreamers. 
This is a resubmission of [this closed PR](https://github.com/SocialiteProviders/Providers/pull/82).
=> GameWisp Provider

src/Weixin/Provider.php
sync with laravel/socialite
compatible with Laravel\Socialite\Two\AbstractProvider::scopes($scopes)
see: [Let user pass a single scope as a string](https://github.com/laravel/socialite/commit/63e6baba3da1a24267a72ee9f36e418d35402c9b)
=> remove weixin provider scopes function

src/Discord/Provider.php
mapUserToObject function was removing the leading 0 from username "%s#%d" because it was being seen as an integer rather than a string.
=> Update mapUserToObject to accept discriminator as string

src/Yammer/Provider.php
Yammer's current implementation tries to use `json_decode` on the body while parsing the token, although it's already an array. I've fixed that.
=> [Yammer] Fix token parsing

src/Flickr/Server.php
Where the original would use a 'json()' method on the request, this was undefined. Hence, it now takes advantage of the 'json_decode()' function. Furthermore, the response I received did not contain a 'realname' entry and thus was throwing an NPE, a check is now in place to check for this field.
=> Fixed NPE and JSON for Flickr provider

src/Meetup/Provider.php
Today I've tried to request multiple scopes with the meetup provider. Unfortunately that didn't work as expected, I always got an `invalid_scope` error. 
So I looked in the documentation at https://www.meetup.com/de-DE/meetup_api/auth/#oauth2-scopes and found out that we have to separate the scopes with an `+`. 
It really needs to be `+` so we have also to `urldecode` the URL. 
With this changes the provider works as expected even if you request multiple scopes.
=> modify meetup provider to allow requesting of multiple scopes

src/Twitter/Server.php
TwitterProvider(Oauth1) doesn't compatible an additional query string regardless of having a method with().
Laracast discussion 'Is it possible to use force_login for Twitter in Laravel Socialite?'.
https://laracasts.com/discuss/channels/laravel/is-it-possible-to-use-force-login-for-twitter-in-laravel-socialite
I updating method getAuthorizationUrl().
It allows additional query strings like calling with(['fource_url'=>true]) options as well as ['lang' => 'ja'] option.
if 'SocialiteProviders\Manager\OAuth1\Server' add this function, It might be compatible any other OAuth1 providers.
Please review it. thx.
=> TwitterProvider(OAuth1) additional query string

src/GitLab/Provider.php
`scopes` array in GitLab provider has empty string by default.
if the scopes ```['', 'read_repository']```
(by ```\Socialite::driver('gitlab')->scopes(['read_repository'])->redirect();```)
the query strings will be like ```&scopes=%2Cread_repository```
but I want ```&scopes=read_repository```
therefore the empty string should be deleted.
=> GitLab provider: `scopes` array should not have empty string

src/Discord/Provider.php
Currently, the Discord provider doesn't take into account when email OAuth scope is not selected and throws an exception.
When using `identify` and excluding `email` scopes, Discord provider tries to retrieve `email` array key within `mapUserToObject()` without checking if `email` exists.
=> Fixed Discord provider not allowing user without email

src/Shopify/Provider.php
This change allows the Shopify subdomain to be retrieved from the parameters if it exists.
This makes it easy to use the Provider via the Socialite facade e.g.
```php
return Socialite::with('Shopify')
->with([ 'subdomain' => $request->shopify_url ])
->redirect();
```
rather than having to redeclare a full config object, e.g.
```php
$config = config('services.shopify');
$config = new \SocialiteProviders\Manager\Config(
$config['client_id'],
$config['client_secret'],
$config['redirect_url'],
['subdomain' => $request->shopify_url]
);
return \Socialite::with($this->driver)->setConfig($config)->redirect();
```
=> Allow retrieval of subdomain from a parameter

src/Twitch/Provider.php
The scope "user_read" no longer returns a value for email under API  v3 and v5.   The "new" twitch API requires the scope "user:read:email" to obtain the email address.
Note: The default version of the API is v3 until Dec. 31, 2018. However, both v3 and v5 are deprecated and will be removed altogether at the end of 2018.
Reference:  https://dev.twitch.tv/docs/authentication/#scopes
=> Updated scope request for twitch due to new API

src/Battle.net/Provider.php
Blizzard's Battle.net API is region sensitive. The problem at hand is that we currently can only set the region statically in the config making it impossible to host the same site for people with e.g. EU and US accounts.
This adds the possibility of dynamically setting the region during runtime if necessary. If nothing is set it will default to what is specified in the config.
=> Allow override of Battle.net region via provider

src/LaravelPassport/Provider.php
Laravel passport uses a space separator between different scopes in the authorization request. From the documentation: "The scope parameter should be a space-delimited list of scopes" (https://laravel.com/docs/5.6/passport#assigning-scopes-to-tokens)
=> Override scope separator to use space instead of comma.

src/Microsoft/Provider.php
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md#properties
| Property       | Type    |Description|
|:---------------|:--------|:----------|
|mail|String|The SMTP address for the user, for example, "jeff@contoso.onmicrosoft.com". Read-Only. Supports $filter.|
|userPrincipalName|String|The user principal name (UPN) of the user. The UPN is an Internet-style login name for the user based on the Internet standard RFC 822. By convention, this should map to the user's email name. The general format is alias@domain, where domain must be present in the tenant’s collection of verified domains. This property is required when a user is created. The verified domains for the tenant can be accessed from the **verifiedDomains** property of …
=> fix email should be userPrincipalName attribute

src/Microsoft-Graph/Provider.php
This change was made to accommodate the ability to configure the tenant that you are authenticating against in the graph api. It covers the case where you would prefer to use the tenant specific profile for a guest user. I.E. All users authenticating to my application must be in the same tenant on Microsoft.
I discovered this issue when I attempted to add a guest user to my (multi-tenant) application. Since the application I'm working on maps it's tenants to Microsoft graph tenants I wanted to ensure that the guest user that was logging into my application does in fact have an account on the corresponding Microsoft tenant. With the common login endpoint the user was being returned with an id that did not match the user listing specific to a tenant. To resolve this I had to update to …
=> [Change] Introduces the Ability to Login to a Specific (Microsoft Graph) Tenant

src/Trello/Provider.php
I replaced the default null values for the according fields.
If you want to access the email address, you have to pass the `account` scope.
=> Trello: Added id, name, email and avatar

src/UFS/Provider.php
The UFS provider now supports both production and development mode URIs. Also, more user fields are working now.
A PR to the docs repo was submitted too with the new config available.
=> UFS Provider - URI based on environment and more user fields

src/Battle.net/Provider.php
As Blizzard recently switched to their new developer portal they also change their endpoints a little. One of those changes was to change the endpoint to retrieve user infos (as referenced here: https://develop.battle.net/documentation/guides/using-oauth/authorization-code-flow).
=> Change Battle.net user info URL

src/Harvest/composer.json
Latest version of "socialiteproviders/manager": "^3.3"
Error without this modification:
- socialiteproviders/harvest v1.0.0 requires socialiteproviders/manager ^2.0 -> satisfiable by socialiteproviders/manager[2.0.x-dev].
=> Update for compatibility with manager

src/Harvest/composer.json
Latest change not work for socialiteproviders/manager 3.3
```
Installation request for socialiteproviders/harvest ^1.0 -> satisfiable by socialiteproviders/harvest[v1.0.0].
- Installation request for socialiteproviders/manager (locked at v3.3.1, required as ^3.3) -> satisfiable by socialiteproviders/manager[v3.3.1].
```
=> Upgrade to manager 3.3

src/Acclaim/composer.json, src/App.net/composer.json, src/Microsoft-TeamService/composer.json, src/Teamleader/composer.json, src/UCL/composer.json
These providers were broken:
- Microsoft-TeamService
- App.net
- Acclaim
- UCL
- Teamleader
PSR-4 autoloader tried to find sources in not exists `/src` directory.
Additionally I've found that these 2 Providers don't have split repositories (but it exists in split.sh):
- UCL
- Teamleader
=> Fix broken PSR-4 autoloader

LICENSE, composer.json
This PR resolves https://github.com/SocialiteProviders/Manager/issues/132
Because all the providers have same directory architecture now - we can register root `src` directory as `SocialiteProviders\\`. PSR-4 autoloader should handle this correctly.
If new package called `socialiteproviders/providers` will be added in Packagist - then by pulling it into the application we will be able to use any provider we want without separate packages installations.
Additionally I've updated year in license file.
=> Add root composer.json file

src/Bitbucket/Provider.php, src/Facebook/Provider.php, src/GitHub/Provider.php
These providers extends stock Socialite providers. It will be better to additionally set that they are implements `SocialiteProviders\Manager\Contracts\OAuth2\ProviderInterface` interface too.
=> Providers from stock should implement manager interfaces

src/Steam/Provider.php
Hey. I made a few changes to Steam provider for it to be easier to both test and use:
- changed private to protected, to allow to overwrite the method if needed
- changed direct config references (to 'redirect' and 'client_secret') to corresponding class properties, so they can be set using socialite's default methods. That's how it works in other providers
- overwritten additionalConfigKeys method to allow the use of 'proxy' config value
All of the changes should be safe. I would be thankful if you could merge and release the changes as soon as possible, because there's no way I know of to pull from forked splitted repo.
=> Fixes to Steam provider

src/Strava/Provider.php
As per the Strava docs
January 15, 2019
Email address is no longer part of the profile:read_all scope and is removed from the athlete model.
=> Fixed Undefined index error in Strava provider

src/LinkedIn/Provider.php
So v2 is LinkedIn's API is far more convoluted.
I ended up having to do two requests. A separate request needed to be done for the primary email address. Here are some pertinent docs
https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api?context=linkedin/compliance/context
https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/primary-contact-api?context=linkedin/compliance/context
Getting a usable avatar URL was also much more tricky. I had to add a URN id which returns a collection of usable avatars of varying sizes. I ended up popping off the last one, which is the largest size available.
This could probably use some array key checking... this API is heavily nested.
=> Switched to api v2

src/Mattermost/Provider.php
If user is using a default Mattermost avatar, then `last_picture_update` will not be accessible.
=> Fix missing Mattermost avatar fatal error

src/Stripe/Provider.php
Per the Stripe API Changelog (https://stripe.com/docs/upgrades#api-changelog):
As of the 2019-02-19 release
> The display_name and timezone fields have been moved to settings[dashboard].
=> Stripe api change 20190219

src/Vimeo/Provider.php
Vimeo authentication supports scopes, so I just added the properties for default scope, and separator in order to make it work.
See Vimeo doc for more about scopes: https://developer.vimeo.com/api/authentication
=> Added scopes for Vimeo Authentication

src/WeChatServiceAccount/Provider.php
Reverts SocialiteProviders/Providers#311
the code is wrong!
should set config and env:
`config/services.php`
```
'wechat_service_account' => [
'client_id' => env('WECHAT_SERVICE_ACCOUNT_APP_ID'),
'client_secret' => env('WECHAT_SERVICE_ACCOUNT_APP_SECRET'),
'redirect' => env('WECHAT_SERVICE_ACCOUNT_CALLBACK_URL'),
'scopes' => preg_split('/,/', env('WECHAT_SERVICE_ACCOUNT_SCOPES'), null, PREG_SPLIT_NO_EMPTY),
'union_id_with' => preg_split('/,/', env('WECHAT_SERVICE_ACCOUNT_UNION_ID_WITH'), null, PREG_SPLIT_NO_EMPTY),
],
```
`.env`
```
WECHAT_SERVICE_ACCOUNT_APP_ID=wx222
WECHAT_SERVICE_ACCOUNT_APP_SECRET=zxcv
WECHAT_SERVICE_ACCOUNT_CALLBACK_URL="http://example.com/login/wechat-service-account/callback"
WECHAT_SERVICE_ACCOUNT_SCOPES=unionid …
```
=> Revert "Fixed bug so that user id can be unionid"

src/Flickr/Server.php, src/Google/Provider.php, src/Kakao/KakaoProvider.php, src/Okta/Provider.php, src/Orcid/Provider.php, src/Steem/Provider.php, src/Twitch/Provider.php, src/Untappd/Provider.php
`array_get` helper method is deprecated and will be removed in Laravel 5.9.
This PR replaces it with `Illuminate\Support\Arr::get`.
=> Remove deprecated Laravel helper methods

src/Google/Provider.php
This PR removes `ProviderInterface` from Google `Provider` because it's already defined in parent class.
This provider was added in #266 but it always throws an exception:
> Interface 'SocialiteProviders\Google\ProviderInterface' not found
=> Fix Google Provider ProviderInterface

src/Google/Provider.php
This PR changes identifier from `GOOGLEOAUTH` to `GOOGLE` to follow same convention with other providers.
Google-Plus provider wasn't followed naming convention and used `GOOGLE` identifier. But now Google-Plus should be replaced with Google provider and this change might be even better because there will be no need to change identifier from old Google-Plus to new Google provider.
Since issue #317 exist - nobody started to use this provider and this could be changed without breaking changes.
=> Fixes google provider identifier

src/Naver/NaverProvider.php
closed #339 
In this PR changed to call the `__toString` method of the` GuzzleHttp \ Psr7 \ Stream` class when reading XML of Naver user information response.   
This will reread the stream from the beginning.
=> Fix parse xml for Naver user

src/Kakao/KakaoProvider.php
closed #342  
This PR has been changed to work properly even if the 'properties' field of Kakao user is empty.
=> Fix properties field may be empty of Kakao user

src/Microsoft-Graph/Provider.php
This was originally proposed in the read-only split of the Microsoft Graph repo [here](https://github.com/SocialiteProviders/Microsoft-Graph/pull/3), but the user who created the PR no longer exists.
From that PR...
> For example, Outlook user is not obligated to fill out the given name field, in that case we don't get response with givenName value therefore givenName index is undefined.
> 
> Similar situation was with Github provider, following commit [laravel/socialite@38c15dc](https://github.com/laravel/socialite/commit/38c15dc9ec9cd0132e45b3228e20eed8832bf9f3) set null as email index value if email is undefined.
In addition to that PR, I have changed from `array_get` to `Arr::get()` because the global array helpers are deprecated in 5.8 and will be removed in 6.0
=> Some array keys may be undefined for Microsoft Graph

src/Microsoft-Graph/Provider.php
This PR adds support for using the `tenant_id` config key from within the `config/services.php` file, such as...
```
'graph' => [
'client_id' => env('GRAPH_KEY'),
'client_secret' => env('GRAPH_SECRET'),
'tenant_id' => env('GRAPH_TENANT_ID'), // <-- Can now be declared here
'redirect' => env('GRAPH_REDIRECT_URI'),
],
```
Currently, it is only possible to add the tenant id by chaining it as follows...
```
Socialite::with('graph')
->setTenantId(config('services.graph.tenant_id'))
->redirect();
```
=> Add tenant_id to config keys array for Microsoft Graph

.github/workflows/monorepo-split.yml
After a ton of debugging, I finally figured out why the splitting doesn't work in actions. When actions checks out a branch, it ends up on a detached head version of that branch. Plenty of others have issues with this as well: https://github.com/actions/checkout/issues/6
I'm leaving this as a draft for the moment as currently you need to supply an access token that has write permissions to all of the target repos. If the deploy fails, it ends up in the logs (not good!).
I'll have a go at switching it to use an SSH key (but then the CI will have access to any private repos of the person who creates it) but ideally we'd have a better way to ensure it remains secret, so will look into that.
cc @m1guelpf
=> fix: fix automatic splitting failure

monorepo-builder.yml
This fixes a failure in the splitting script because the repo isn't actually called `Google`, it is `Google-Plus`
```
remote: Repository not found.                                                
fatal: repository 'https://github.com/SocialiteProviders/Google.git/' not f  
ound                                      
```
=> fix: fix google repo URL

src/Twitch/Provider.php
Closes #411 
See https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916
=> Change twitch user request according to new policy

src/Keycloak/Provider.php
Fix `Arr::get()` usage.
Actually this provider is not working, when getting `user`
=> Fix Keycloak provider 

src/Microsoft/MicrosoftAvatar.php, src/Microsoft/MicrosoftUser.php, src/Microsoft/Provider.php
The Microsoft Graph API does not provide a URL to the users avatar from what I can tell. Microsoft actually returns the full binary avatar at the endpoint 'https://graph.microsoft.com/v1.0/me/photo/$value'.
Docs: https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0#get-the-photo
This change makes an additional request to get the binary data and save it as the 'avatar_base64' property. Since it doesn't look like any other providers return the actual avatar and just link to the avatar URL, I'm not sure how maintainers would prefer to name the property. The 'avatar' property is left null since there's no public avatar URL.
=> [Microsoft] Get avatar.

src/SciStarter/Provider.php
This PR replaces the default comma scope separator with spaces, as required by the SciStarter API.
=> Update SciStarter scope separator

src/LaravelPassport/Provider.php
When using socialite to get a user from a token, there is an assumption that the token is *always* valid.
In fact, baked into Socialite, the `userFromToken` call is expected to return an instance of `\Laravel\Socialite\Two\User`.
However, if the Passport token you have for the user is no longer valid (for example, the token has expired or been revoked) then the call to the `/api/user` endpoint will actually redirect you to a login form due to the Passport auth driver on your authentication application.
The current implementation of `getUserByToken` will subsequently return `null` if it does not get JSON returned and this will cause Socialite to blow up internally when it receives `null` instead of an array when it calls `mapUserToObject`.
By simply casting the result to an array, we will …
=> [Passport] Make getUserByToken always returns an array

src/Steam/Provider.php
Currently when not using HTTPS (for example in dev environment) Steam provides the error "realm and return_to do not match" causing OpenIDValidationException to be thrown.
This PR stops the hardcoding of HTTPS for the 'realm' parameter, and instead uses HTTPS when the original request was made using HTTPS.
This PR also adds the error from Steam into the OpenIDValidationException message.
Thanks!
=> [steam] Fix "realm and return_to do not match" when using HTTP

src/Discord/Provider.php
Although Discord said the discordapp.com domain will stick around for a while, developers should start updating the domain to discord.com instead of discordapp.com
=> Update to new Discord domain

src/Apple/Provider.php
Hey there! 👋 
The current encoding used to generate URL by the Apple Provider make it fails on mobile.
The scopes should be separated with a space, and the default encoding will use a `+`.
=> Apple: Switch Query Encoding type to RFC3986

src/Steam/Provider.php
With a heavy load, steam bans IP for a while.
=> Ability to use proxies when requesting

src/Yahoo/Provider.php
Since OpenID2 will be EOLed on 6/30/20,
We need to migrate from OpenID2 to OpenID Connect API
https://developer.yahoo.com/oauth2/guide/OpenID2/
SocDir (Social Directory Web Service) also EOL date is June 30, #2020
https://developer.yahoo.com/oauth/social-directory-eol/
=> Migrate to Yahoo Oauth 2.0 API

src/QuickBooks/Provider.php, src/QuickBooks/composer.json
This PR fixes Quickbooks provider scopes by defining the scopes as an array of strings instead of one long string and by defining the `scopeSeparator`. 
The current implementation is broken because the default `scopeSeparator` is a comma, which triggers an `invalid_scope` error with QuickBooks when trying to customize scopes with `->scopes()` or `->setScopes()`.
In addition, it removes the extra scopes (`com.intuit.quickbooks.accounting`, `phone`, `address`) that are not relevant to getting basic user details. The idea is to keep the default scopes to a minimum while still being useful. This follows the example of the core Socialite providers as well as most of the other extra providers in this repo.
Finally, there are a few code style tweaks as well.
=> Fix quickbooks provider scopes

src/Yahoo/Provider.php
Sorry, a later found bug which will lead to fatal when redirect_url is oob need to be fixed.
https://developer.yahoo.com/oauth2/guide/flows_authcode/
=> fix bug when yahoo redirect_url is oob

src/InstagramBasic/Provider.php
The new Instagram Basic Display API is a bit of a pain - it effectively has two scopes, *both* of which require manual review from the Facebook team. Manual review requires a screencast that shows exactly how you intend to use the data from the API, as well as a sandbox app that the review team can test your integration with.
The first scope is `user_profile` which is just what it sounds like, and the second scope is `user_media`, which gives you access to the user's media.
As it is now, the provider uses both scopes and would therefore require your app to use both parts of the API and expose them to users so they appear in the review screencast and sandbox app.
My suggestion here is that out of the box we use the bare minimum scope so we don't force people to go through app review for …
=> Instagram Basic: remove default fields/scopes

src/Microsoft/Provider.php
Currently the `getTokenUrl` method is hardcoded to use the `common` tenant instead of the one configured by the user. This caused the token retrieval to fail for me, as I restricted my app to only personal accounts which requires you to use the `consumer` 'tenant'. Respecting the configured tenant fixes this.
=> Microsoft: use configured tenant in getTokenUrl method

src/DigitalOcean/Provider.php, src/Goodreads/Server.php, src/Jira/Server.php, src/Meetup/Provider.php, src/Netlify/Provider.php, src/Okta/Provider.php, src/Opskins/Provider.php, src/PeeringDB/Provider.php, src/Rdio/Server.php, src/Steam/Provider.php, src/Withings/Server.php
Some provided URLs are not secure.
This PR ensures that all URLs use `https`.
This PR also updates some links to the provider documentation.
=> Always use https

src/Apple/Provider.php
Replace the call to `filled()` with a simpler non-empty string check as it's only available in Laravel>=5.5 and throws a `BadMethodCallException` in Laravel 5.4
This is necessary because this library has a dependency to socialiteproviders/manager which allows installation in Laravel 5.4 in the latest version
=> Refactor SocialiteProviders\Apple\Provider::mapUserToObject()

monorepo-builder.yml, src/ThirtySevenSignals/Provider.php, src/ThirtySevenSignals/ThirtySevenSignalsExtendSocialite.php, src/ThirtySevenSignals/composer.json
Reverts SocialiteProviders/Providers#499
Turns out the provider is just name wrong, it's actually used for basecamp 🙈
=> Revert "fix: remove 37signals provider"

src/Auth0/README.md
The `base_url` is an additional configuration value used by this package's provider, but not yet documented, leaving incomplete installation instructions.
=> Add note about adding the base URL for authorization

src/Apple/Provider.php
Current implementation performs an `openssl_pkey_get_details` and a `$token->verify` against all JWK keys distributed by Apple. This is time-consuming and can be optimized. 
Apple provides in its JWT token the `kid` claims describing which JWK key has been used for token signing, and therefore which JWK key should be used for token signing verification.
https://developer.apple.com/documentation/sign_in_with_apple/fetch_apple_s_public_key_for_verifying_token_signature
> The endpoint can return multiple keys, and the count of keys can vary over time. From this set of keys, select the key with the matching key identifier (kid) to verify the signature of any JSON Web Token (JWT) issued by Apple. For more information, see the JSON Web Signature specification.
This PR updates `Provider::verify` …
=> Avoid unnecessary key check if token kid doesn't match

src/Twitter/README.md
Twitter login won't work without this step and will return a vague error instead.
=> Added necessary step to Twitter docs

src/Apple/Provider.php
This pull request fixes https://github.com/SocialiteProviders/Providers/issues/530 introduced by PR https://github.com/SocialiteProviders/Providers/pull/528. 
The `kid` claim (key Id) is always provided in header section of a JWT token, and wrong assumption was made about ability of retrieving this value using the `getClaim()`method of lcobucci/jwt library.
As guessed by @arun07as, using [getHeader()](https://github.com/lcobucci/jwt/blob/3.3.3/src/Token.php#L106) method resolve the issue.
=> Fix JWT kid reading

src/Keycloak/Provider.php
=> fix: keycloak scope separator

src/Streamlabs/Provider.php, src/Streamlabs/README.md
This PR allow developers to access the third-party accounts that the user signed-in with Streamlabs, so they can access more information (such as nicknames, profile picture, ...). Documentation has been updated as well.
Documentation: https://dev.streamlabs.com/reference#user
=> feat(streamlabs): add third-party accounts

src/Dropbox/Provider.php, src/Dropbox/README.md
Dropbox uses a space for multiple scopes.
Updated documentation to include the proper usage with the base default scope because not specifying any scopes will result in an error message.
=> Dropbox scope separator, updated docs

src/YouTube/Provider.php
Following changes from Google, OAuth2 endpoints have been updated.
Documentation: https://developers.google.com/youtube/v3/guides/auth/server-side-web-apps#obtainingaccesstokens
=> fix(youtube): update oauth2 urls

src/Zoho/Provider.php
In some instance, Zoho will return which accounts server to use to get further user's details.
For example, our customer in Europe is instructed to use https://accounts.zoho.eu (instead of .com) 
This change is about using the `accounts-server` provided by Zoho, if any. Otherwise will use the same as today by default.
Note, in my tests, the initial authUrl `getAuthUrl()` does not need to be taylored to the user's instance.
Thanks for massive amount of work done on Socialite!
Best Regards, 
Colin
=> Use Zoho-provided accounts server when provided

src/GitLab/Provider.php
This PR is intended to fix an issue originally found in BookStackApp/BookStack#2359 where the GitLab provider cannot be used without either:
* Using a very wide permission scope (Complete read/write access);
* Overriding the scopes on the provider.
Currently, when authenticating GitLab will show the below error unless the `api` scope is set on the "Application" created within GitLab.
> The requested scope is invalid, unknown, or malformed.
The `api` scope is described by GitLab as so:
> Grants complete read/write access to the API, including all groups and projects, the container registry, and the package registry.
Of course this much broader than the details we need, which can instead be covered by the `read_user` scope which is described like so:
> Grants read-only access to the …
=> Add default scope to the GitLab Provider

src/SURFconext/Provider.php, src/SURFconext/README.md
Tried using this SocialiteProvider earlier today and it was not working. Decided to do some digging, temporarily add some code in our project to make it work. Everything is working now so decided to create a PR to get this changed structurally.
A few keynotes:
- SURF changed their endpoints and usage of old endpoints would lead to [a redirect to their docs regarding the migration](https://wiki.surfnet.nl/display/surfconextdev/OpenID+Connect+Migratie).
- Decided to document the optional test key as it was hidden now.
=> SURFconext: Change URLs and keys to reflect changes done by SURF

src/Mixcloud/Provider.php
The Mixcloud provider was broken, as it was attempting to use a deprecated method to obtain the access token – `Laravel\Socialite\Two\AbstractProvider::getAccessToken()` – which was removed in [this commit](https://github.com/laravel/socialite/commit/0c234df124df24eed19355949d412ce66cee26fc#diff-8d3fd95aa368bbc8b78e7755afdf6132dbab48487f3f53591e55bf3f757f7121).
This PR updates the code to use the latest method(s), resolving issue #589.
=> Fix parsing of Mixcloud access token

monorepo-builder.yml, src/Fablabs/FablabsExtendSocialite.php, src/Fablabs/Provider.php, src/Fablabs/README.md, src/Fablabs/composer.json
Adds support for using [fablabs.io](https://fablabs.io/about) as a login provider
=> Add Fablabs.io provider

src/Zoom/Provider.php
Turns out Zoom does not send the `pic_url` field if you do not have one set in their platform 🤷
=> Adds null fallback for avatar as zoom does not send it if it does not exist

src/Telegram/Provider.php
when a telegram user doesn't have `username` or `photo_url`, replace them with `first_name` and `null`
=> fix: incomplete telegram user data

src/Okta/Provider.php, src/Okta/README.md
This PR fixes a recent change (https://github.com/SocialiteProviders/Providers/pull/520) that broke existing functionality for Okta users who do not use a custom Auth Server ID or the Okta Developer product.
The changes in the above PR were valid for users of the Okta Developer (https://developer.okta.com/) product but caused a breaking change for users of Okta (https://www.okta.com/uk/workforce-identity/).
Specifically it is the Okta OIDC connect integration that is now broken due to the inability to set an empty `auth_server_id` as there is an extra `/` present in the URL. 
Details of the Okta OIDC integrations can be found on the help page here: https://help.okta.com/en/prod/Content/Topics/Apps/Apps_App_Integration_Wizard_OIDC.htm
Based on the `.well-known/openid-configuration` for an …
=> Allow Okta Auth Server ID to be empty for use with Okta OIDC app integration

composer.json, src/Twitter/Server.php
```php
Declaration of SocialiteProviders\Twitter\Server::getAuthorizationUrl($temporaryIdentifier) should be compatible with League\OAuth1\Client\Server\Server::getAuthorizationUrl($temporaryIdentifier, array $options = Array)
```
`League\OAuth1\Client\Server\Server::getAuthorizationUrl` was changed paramater, added `$options` and when installing was failed, please merge it, thanks.
=> Twitter Compatible with OAuth1 client method

src/Kakao/KakaoProvider.php
There was a problem with client_secret not being used by `KakaoProvider`, so I fixed it.
Kakao uses client_secret optionally, `client_secret` field only added if it exists.
=> fix: incomplete token fields in kakao provider

src/MercadoLibre/Provider.php
I realized that returns from the free market are not sending the thumbnail index so I set it to null if these indexes do not arrive because I was returning an error when trying to retrieve the authenticated user's data.
I would like you to evaluate this PR, and see if this change is valid.
=> Fix indice avatar with null in mercado libre provider

src/Microsoft/Provider.php
Added support for Microsoft Ads, which requires `scope` to be included in the `POST` request to the token url.
Fixes #637
See the example:
https://docs.microsoft.com/en-us/advertising/guides/get-started?view=bingads-13#quick-start-production
```powershell
$response = Invoke-WebRequest https://login.microsoftonline.com/common/oauth2/v2.0/token -ContentType application/x-www-form-urlencoded -Method POST -Body "client_id=$clientId&scope=https://ads.microsoft.com/ads.manage%20offline_access&code=$code&grant_type=authorization_code&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient"
```
PS: sorry for the PR inside Microsoft repository, seems like I did that wrong :)
=> Microsoft Ads is now compatible with Microsoft provider.

src/HubSpot/Provider.php
The database table "connected_accounts" in joelbutcher/socialstream require a name and function "findConnectedAccountForProviderAndId" requires an ID user from provider.
fix: https://github.com/SocialiteProviders/Providers/issues/640
=> fix: HubSpot compatibility problem with joelbutcher/socialstream

src/Apple/Provider.php
I'm currently using the Apple provider for social login from a mobile app, which communicates with a Laravel API at the back-end.
The app authenticates with Apple first, and I verify with Apple (with Socialite) that the app is sending valid IDs and name, before persisting the state in a DB.
I'm facing an issue whereas the Apple provider at https://github.com/SocialiteProviders/Providers/blob/master/src/Apple/Provider.php#L205 tries to cast to string (to be later JSON-decoded) an associative array, which makes Socialite crash at that line with an error `Array to string conversion`
This PR aims at catching that case, together with isolating the logic for getting the user from the request.
Let me know if there is anything I need/can do in terms of CI/tests :)
Closes #643
=> [Apple] Add support for a `user` as an associative array in Apple provider

src/Adobe/Provider.php
Remove useless interface, as `AbstractProvider` already implements `ProviderInterface`.
=> Remove useless interface.

src/Gumroad/GumroadExtendSocialite.php
=> Prefer ::class notation.

src/Fablabs/Provider.php, src/Gitea/Provider.php, src/Pixnet/Provider.php
Those properties are overridden with the same values and can be safely removed.
=> Remove useless class properties

src/QuickBooks/README.md
Hey,
I've noticed that an important parameter is missing. Without `env`, you can't actually test it locally as the production environment will be called. The PR adds a hint on the parameter and a note explaining the purpose. Might save someone else a few hours.
Cheers,
Peter
=> Adding missing configuration value to Quickbooks readme

src/SalesForce/README.md
As per: https://github.com/SocialiteProviders/Providers/issues/670#issuecomment-828375326, the name of the driver should be 'salesforce'. Using 'SalesForce' results in a driver not supported error message.
=> Correcting Salesforce driver name in documentation

src/Okta/Provider.php
This PR attempts to fix https://github.com/SocialiteProviders/Providers/pull/672
This typically happens when no `auth_server_id` has been set
=> Fix OKTA token URL.

src/Flickr/Server.php
Currently when using Flickr it will result in the error: "Oops! Flickr doesn't recognise the permission set." - The authorize URL must have perms specified on it:
https://www.flickr.com/groups/51035612836@N01/discuss/72157692896948105/
Docs are here:
https://www.flickr.com/services/api/auth.oauth.html
I have verified that once this is added everything works correctly again.
=> Fixed Flickr doesn't recognise the permission set

monorepo-builder.yml, src/Notion/NotionExtendSocialite.php, src/Notion/Provider.php, src/Notion/composer.json
this PR adds notion oauth driver based on [the documentation here](https://developers.notion.com/docs/authorization)
a small note . notion **doesn't yet have end point** to get the current user so inside **getUserByToken** so i have returned the body response
```javascript
{access_token, workspace_name, workspace_icon, bot_id}
```
=> Add Notion oauth driver

monorepo-builder.yml, src/Saml2/InvalidSignatureException.php, src/Saml2/NotSupportedException.php, src/Saml2/Provider.php, src/Saml2/README.md, src/Saml2/Saml2ExtendSocialite.php, src/Saml2/User.php, src/Saml2/composer.json
This is not an OAuth provider, but it does meet the Socialite specification in terms of implementing the contract by extending `Laravel\Socialite\Two\AbstractProvider`, implementing `Laravel\Socialite\Contracts\Provider` and following the same configuration method.
For testing you should be able to use any SAML provider (Google, Azure), but there is a test service that works here too: https://samltest.id
https://samltest.id is a good example of a service that doesn't implement the HTTP-Redirect part of the specification, as noted in the "SAML Protocol" part of the README.md, but Google, Azure and many others do.
For testing this with samltest.id:
* Install the provider, and configure according to the docs using `https://samltest.id/saml/idp` as the `metadata` value
* Expose the Laravel …
=> Added Saml2 provider

monorepo-builder.yml, src/Atlassian/AtlassianExtendSocialite.php, src/Atlassian/Provider.php, src/Atlassian/README.md, src/Atlassian/composer.json
Differs from existing Jira provider in that it uses OAuth 2 as documented at https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/
=> Create Atlassian provider

src/Teamleader/Provider.php
The Teamleader application has been renamed to Teamleader Focus, more info about this can be found [here](https://www.teamleader.eu/blog/new-names-teamleader-focus-orbit). This product name change also means that the application, api, marketplace, etc. have a new home under [focus.teamleader.eu](https://focus.teamleader.eu).
This PR changes the Teamleader URLs in this repo to point to [focus.teamleader.eu](https://focus.teamleader.eu). The switch to these new URLs isn't urgent though, the old URLs will remain available for some time.
=> Change teamleader urls to focus.teamleader.eu

src/Azure/Provider.php
When we switched from PHP 7.3 to 7.4.20 we started getting an error message with the Azure Service Provider. It appears that in PHP 7.3 the code `$this->config['tenant'] ?: 'common'` resulted in a notice but in 7.4 it throws a warning which results in a 500 error. Adding an `isset()` check for the tenant property fixes the problem.
Error message when tenant config is not set:
```
2021-06-11 18:07:21] staging.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/html/vendor/socialiteproviders/microsoft-azure/Provider.php:35)
```
=> Checking for tenant config throws warning in PHP 7.4

src/Flickr/Provider.php, src/Flickr/Server.php
additionalConfigKeys in Server is never called, and thus `perms` is never available. By moving it to `Provider.php` it then allows `perms` to become available after which `Server.php` can then obtain it correctly with `getConfig`
=> Move Flickr additionalConfigKeys to Provider so that it sets config correctly.

src/Stripe/Provider.php
The $email variable was not being used anywhere, Imho there is no need for the extra verbosity unless a case where there might be different api versions or similar like the display name
=> Remove unused code on Stripe provider

src/Apple/README.md
The post from Okta explains how to configure Sign In with Apple and get it working.
The issue is that the statically generated JWT token that they use has a maximum lifetime of 6 months (a rule from Apple). I recently wrote about an approach off the back of the Okta article on generating the client secret for each request to ensure you never face an issue with the client secret expiring.
=> [Apple] Update README.md to note the client secret JWT expiry

src/TikTok/Provider.php
Line 43 of TikTok Provider.php accesses an undefined property:
https://github.com/SocialiteProviders/Providers/blob/77796034c2d5be3fdfbf6a839725e5387234e7bb/src/TikTok/Provider.php#L43
This PR is to resolve ErrorException: Undefined property: SocialiteProviders\TikTok\Provider::$user
=> Resolve TikTok Provider ErrorException.

src/SoundCloud/Provider.php
SoundCloud updated their OAuth flow to use a token in the header, instead of passing it via the query string.
More info here: https://developers.soundcloud.com/blog/security-updates-api
=> Update SoundCloud to newest security patch

src/Microsoft/Provider.php
This PR adds the ability to add application-specific requests for custom fields from the Microsoft provider. This allows for the use of fields like on-premise Active Directory extension attributes, which is my use case for it, but also any other field on the Microsoft Graph that an application might need to access.
=> Add ability to request custom fields from Microsoft

src/Keycloak/Provider.php, src/Keycloak/README.md
Adds a Keycloak provider method that returns a logout endpoint in line with the [Keycloak logout documentation](https://www.keycloak.org/docs/latest/securing_apps/index.html#logout).
=> Add getLogoutUrl for Keycloak provider

src/Saml2/Provider.php
When implementing SAML2 configuration to work with jumpcloud.com as Identify Provider, I realised their SSO binding method is a "POST" and not a "REDIRECT". 
Problem: Redirect method is hardcoded in the code. 
Solution : This change makes it configurable in the services.php file. It is backward compatible as it takes the current value as default.
=> Make SAML2 binding configurable & fix regression introduced by #712

src/SURFconext/Provider.php
Adds support for [SURFconext Teams](https://wiki.surfnet.nl/pages/viewpage.action?pageId=10132152) by including the `isMemberOf` claim to the current set of mapped attributes.
See: https://wiki.surfnet.nl/display/surfconextdev/Attributes+in+SURFconext#AttributesinSURFconext-isMemberOfisMemberOf
=> Add support for isMemberOf claim to SURFconext provider

src/ProductHunt/Provider.php, src/ProductHunt/README.md, src/ProductHunt/composer.json
This PR updates the ProductHunt driver to use the [v2](https://api.producthunt.com/v2/docs) API since v1 is now [deprecated](https://api.producthunt.com/v1/docs). This means the users' email is no longer returned, I've opened an [issue](https://github.com/producthunt/producthunt-api/issues/247) in ProductHunts' producthunt-api repo related to that since it was included in v1, so I've asked if it could be added to the v2 GraphQL [User Schema](http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/object/user/). If it gets added I'll update the provider again. 
This PR also fixes the driver since the PSR-4 namespace was sadly wrong so Composer autoloaded the driver under the `SocialiteProviders\AngelList` namespace instead of `SocialiteProviders\ProductHunt` causing a …
=> Update ProductHunt API to v2

src/Keycloak/Provider.php
The given_name on keycloak is user attribut "firstName" by default and is not possible to replace this mapper to give full name.
To get full name you need to call name
See Socialite request full name
https://github.com/laravel/socialite/blob/b5c67f187ddcf15529ff7217fa735b132620dfac/src/AbstractUser.php#L25
=> Change given_name (is firstName on keycloak) to name

src/QQ/README.md
This PR fixes the issue in https://github.com/SocialiteProviders/Providers/issues/775, where the namespace in the event provider does not match the actual class name. Notice the double uppercase Q's in the example as opposed to the single uppercase in the class name.
https://github.com/SocialiteProviders/Providers/blob/85f27b5b069a6fc676b428c24513a97394cf18ec/src/QQ/QqExtendSocialite.php#L7
=> Fix wrong event provider namespace in QQ's README.

src/Saml2/Provider.php
Noted in #791, recent changes in Socialite Providers prevents the documented installation method from working as-is. This restores the original functionality by making the standard keys "additional", as they are not required for Saml2 configuration.
=> Saml2 provider: Add standard OData config keys as additional keys

src/TikTok/composer.json
I ran into some issues with this constraint installing the TikTok provider with Laravel 9.x.
I can see why the dependency was added - it references a Socialite exception. 
However, other SocialiteProviders that also reference Socialite classes omit `laravel/socialite` from their Composer files. TikTok is the only one that references it. This makes it consistent across the board.
=> Remove socialite from TikTok composer.json

src/Eveonline/Provider.php, src/Eveonline/composer.json
The algorithm argument for the decode function has been removed as of [6.0.0](https://github.com/firebase/php-jwt/releases/tag/v6.0.0)
The [keyset](https://login.eveonline.com/oauth/jwks) contains a key that satisfies the [algorithm](https://github.com/firebase/php-jwt/blob/main/src/JWK.php#L74) for parsing the keys
=> Bump JWT dep for eveonline provider

src/Okta/Provider.php, src/Okta/README.md
Okta is heavily used for internal apps that may be authenticating to
each other in scheduled processes where no user token is involved.
This additional method is a QOL for obtaining a client token to
authenticate in these situations.
For additional context, please see the official okta documentation:
https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/#about-the-client-credentials-grant
=> Added client access token method for Okta

.gitignore, src/Okta/Provider.php, src/Okta/README.md
Okta requires an `id_token` to be supplied to perform a logout via the
browser. Including this property to facilitate logout and potentially
other needed requests.
Updated the respective readme to clarify process and usage.
For additional context, please see official okta documentation:
https://developer.okta.com/docs/reference/api/oidc/#logout
=> Added logoutUrl method and documentation for Okta

src/Okta/Provider.php
I'm realizing it's advisable to be consistent with the existing
conventions for setting the scopes. In all other cases scopes are set as
an array.
Using existing scopes to accommodate for situations where the user might
be registering the provider globally:
```
$provider = Socialite::driver('okta')->setScopes(['offline_access', 'openid']);
```
I believe it still makes sense to allow overrides directly to accommodate for
situations when both:
- a client access token scope would differ from the user scope
- the provider is registered as a singleton
- you're requesting both types of tokens on the same request
granted that seems pretty rare, so perhaps the override isn't necessary.
=> Rework okta client token method for consistency

src/Eveonline/composer.json
As discussed in https://github.com/SocialiteProviders/Providers/issues/813
This PR reverts the following PR: "Re-add firebase/php-jwt v5.2 to composer for eveonline provider (#807)"
This reverts commit 9e494cbfb615866bd6aac4e469fdc007158417f8.
Besides merging this PR and tagging you **must** delete the previous 4.1.0 tag not only on github but on packagist too:
https://github.com/SocialiteProviders/Eveonline/tags
then you can re-tag which should then contain the merged commit/pr with 4.1.0.
If you do not remove the old *4.1.0* tag, composer will still download the broken version from packagist for anyone using the v5 firebase/php-jwt library
=> fix eve jwt issue

src/AzureADB2C/Provider.php
fixes https://github.com/SocialiteProviders/Providers/issues/818
This all feels quite hacky, especially overriding the `redirectUrl` but I didn't manage to figure out another way.
Note I am using SocialStream, so I had to override quite a few things there as well, to pass the policy as a parameter to the `Provider`
```
Socialite::driver($provider)
->with(['policy' => $policy])
->redirect();
```
I hope I sufficiently taken care of backwards compatibility.
=> AzureADB2C: make it possible to define multiple policies

src/Saml2/OasisAttributeNameUris.php, src/Saml2/Provider.php, src/Saml2/README.md, src/Saml2/User.php, src/Saml2/composer.json
This pull request extends the Saml2 provider to support more of the SAML2 standard. Here is a list of all new functionality:
- Full backwards compatibility, **no** breaking changes
- **Singing and encryption**
Many Identity Providers require the signing of requests and providing of a certificate for encryption. The provider can now take a certificate + private key as optional configuration parameters to support this. If they are provided, every outgoing message is signed, and the provider supports decrypting assertions coming from the provider. If the parameters are not provided there is no change in behaviour.
- **Support both `POST` and `REDIRECT` bindings simultaneously while using `POST` as the default**
The current implementation prefers `REDIRECT` over `POST`. I added the option to …
=> Saml2: Extend SAML2 support

src/Microsoft/MicrosoftUser.php
Fixes https://github.com/SocialiteProviders/Providers/issues/824 where a 404 error bubbles up if the avatar doesn't exist
=> Turn off http errors when fetching Microsoft avatars

src/Bitly/Provider.php, src/Minecraft/Provider.php, src/Telegram/Provider.php, tools/close-subtree-prs.php, tools/release-major-version.php, tools/update-repo-descriptions.php
Since we have recently bumped the codebase to `>=7.4`, we can now safely use short arrow closures.
=> Use short arrow closures

.github/workflows/subtree-pr-close.yml
As per #820, the upgrade of https://github.com/actions/checkout v3 has broken the subtree split.
This seems related to the depth (or history) this change allows to get all history for all branches and tags.
=> Do not limit the number of commits to fetch

src/Saml2/README.md
This appears to be a typo as the `logout` method doesn't exist.
I haven't gotten the feature to work yet so maybe @danielztolnai can confirm if the fix that I propose is correct.
=> Fix typo in Saml2 readme

src/Starling/Provider.php
Updates the User returned for Starling, adding the phone and dateOfBirth fields that are returned (according the API docs at https://developer.starlingbank.com/docs#api-reference-1)
description: | Information about an individual account holder
-- | --
title | string example: Mr
firstName | string example: Dave
lastName | string example: Bowman
dateOfBirth | string($date) example: 1968-04-02
email | string example: dave.bowman@example.com
phone | string example: +447700900123
=> add missing Starling user fields

src/Apple/composer.json
upgrade jwt package to support "LooseValidAt"
=> upgrade lcobucci/jwt to 4.1.5

src/TikTok/Provider.php
Hello,
In my application, I would like to have access to the `data.scope` property that is sent by TikTok at the redirection, but when calling the `user()` method on the provider, the `approvedScopes` property is not set so I cannot access them.
My change set this property on the TikTok provider so we can have access to it when getting the user.
=> Set approvedScopes property on user

src/Saml2/composer.json
The `lightsaml/lightsaml` package has been marked as abandoned, with `litesaml/lightsaml` as the suggested replacement.
See [relevant commit](https://github.com/lightSAML/lightSAML/commit/22ac715f3feb499eaa5a8a61c9cd78ae468613f0).
According to the old package's README, the codebase did not change.
=> Update lightsaml/lightsaml with new replacement package

src/Apple/Provider.php
Based on the last updates from Apple, where we should add to the user's ability to delete an account, we also should revoke his tokens [(Apple doc).](https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens) So I think will be good to have this ability out of the box, as the "Okta" provider has. [(Okta)](https://socialiteproviders.com/Okta/#installation-basic-usage)
=> added a request for revoke Apple token

src/Cognito/Provider.php
Removed Cognito provider fields that can cause errors.
Errors were occurring when the Cognito user pool doesn't have these same fields defined.
=> Update Cognito Provider

src/VKontakte/Provider.php
The current stateless property is set to true. This prevents the state option from being used, while setting stateless to false allows it to be used and throws \InvalidStateException as it should work.
=> stateless fixed default

src/Imis/ImisExtendSocialite.php, src/Imis/Provider.php, src/Imis/README.md, src/Imis/composer.json
https://imis.com/
Notes:
- IMIS doesn't strictly follow the OAuth2 standard.
- A refresh token is returned instead of an auth code.
- IMIS can return a guest user with no data, this has been allowed for.
- IMIS doesn't support the userInfo endpoint so a custom query needs to be created on the IMIS site.
=> add IMIS provider

src/Orcid/Provider.php
PHP 8.1.3
laravel/framework 9.8.1
guzzlehttp/guzzle 7.4.2
socialiteproviders/orcid 5.0.0
The original header configuration with header names “Authorization type” and “Access token” lets guzzlehttp throw this error:
“"Authorization type" is not valid header name”
See https://github.com/guzzle/psr7/blob/master/src/MessageTrait.php, lines 227-234.
The correct syntax of the Authorization header is according to developer.mozilla.org in the case of OAuth 2.0 the following:
Authorization: Bearer &lt;token&gt;
See:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#syntax
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes
This seems to be related to the ORCID documentation which unfortunately contains some, to say the least, mistakable …
=> Fixing headers for reading ORCID records.

monorepo-builder.yml, src/FusionAuth/FusionAuthExtendSocialite.php, src/FusionAuth/Provider.php, src/FusionAuth/README.md, src/FusionAuth/composer.json
This PR adds a provider for [FusionAuth](https://fusionauth.io/).  
Docs: https://fusionauth.io/docs/v1/tech/oauth/endpoints
PS: I didn't add any "Add base_url to your .env" disclaimer like Auth0 because FusionAuth could be both self-hosted (99% of the times) or cloud, so it could be a bit misleading the example in that paragraph (?)
=> Add FusionAuth provider

src/Flickr/Server.php, src/Kakao/KakaoProvider.php, src/Steam/Provider.php
Prefer the consistant use of `get` and `post` methods, over `request`.
=> Use get and post methods

src/Adobe/Provider.php, src/Monday/Provider.php
This PR enforces the use of `getHttpClient` method.
=> Use getHttpClient method

src/LaravelPassport/README.md
The "host" entry is vital to getting this to work, as each Laravel Passport provider will be different.
=> Added "host" to LaravelPassport config array

src/PayPal/Provider.php
PayPal have updated their documentation and the previous endpoints are no longer documented anywhere.
They've also made some slight changes to the data being returned: https://developer.paypal.com/docs/api/identity/v1/
=> Update PayPal to use latest endpoints / user info

src/Kakao/KakaoProvider.php
Hi
i am a user appreciate your effort to keep this repository.
i think i found a code to need fix it.
"getAccessToken" function need to return string($code) so it using "parseAccessToken" function. but "parseAccessToken" function get need array but string before parsing json.
it might be a mistake because above the return code, there are already declare array to parse
($this->credentialsResponseBody).
could you please fix this issue?
sorry for my poor english.
sincerely
=> Update KakaoProvider.php to fIx getAccessToken return value

tools/release-major-version.php
The `.github` repository should be excluded.
=> Exclude .github repository

src/Saml2/Provider.php
Fixes #893 - this adds the assertion consumer URL in the authentication request.
=> Saml2: Always provide the consumer URL in the AuthNRequest

src/FranceConnect/Provider.php
Use `Str::random` instead of the deprecated `str_random()` helper.
=> Use Str::random

src/Monday/Provider.php, src/Okta/Provider.php, src/Saml2/Provider.php
Stay consistant, and cast the body to string instead of using `getContents()`.
=> Cast the body to string

src/Saml2/Provider.php
The technique the provider uses at the moment for route matching is very basic, this PR uses the same code Laravel does to do route matching and is much more reliable. Fixes #906
=> Saml2: Fix route matching

src/Authentik/README.md, src/AzureADB2C/README.md, src/Bexio/README.md, src/FusionAuth/README.md, src/Imis/README.md, src/Lichess/README.md, src/Toyhouse/README.md, src/TwitCasting/README.md, src/Webex/README.md
This PR enforces the use of `::class` notation.
=> Always use ::class notation

src/Monday/Provider.php
the monday provider uses the wrong AbstractProvider class. The old class throws a Call to undefined method `SocialiteProviders\Monday\Provider::additionalConfigKeys()` error. Using the SocialiteProviders\Manager\OAuth2\AbstractProvider solves this problem.
=> depency fix in monday provider

src/Starling/Provider.php, src/Starling/README.md
The current Starling provider uses a non-mTLS token endpoint on the staging environment, and the mTLS endpoint for production. Ideally these should align to prevent unexpected surprises on production.
This adds support for a `use_mtls` config variable, allowing the user to toggle mTLS, and adds the missing urls for both staging and production, so you can use one or the other.
=> adjust Starling token url options

src/Etsy/Provider.php
When trying to obtain an access token with the Etsy provider, the Provider::mapUserToObject method tries to map the user's nickname property to the 'login_name' key from the array which is no longer provided by Etsy. It is now replaced by the first name of the users.
=> Replaced missing key in the user data array in Etsy provider

monorepo-builder.yml, src/Vatsim/Provider.php, src/Vatsim/README.md, src/Vatsim/VatsimExtendSocialite.php, src/Vatsim/composer.json
Provider for [VATSIM](https://vatsim.net/), a flight simulation network
Documentation: https://github.com/vatsimnetwork/developer-info/wiki/Connect
List of scopes available here: [Connect Redirect the User](https://github.com/vatsimnetwork/developer-info/wiki/Connect-Redirect-the-User)
The OAuth servers support required scopes. These are scopes the user cannot opt out from upon approving the application. The methods for setting the required scopes are pretty much an identical copy of the default scopes methods.
Set `services.vatsim.test` to `true` to use the auth-dev.vatsim.net endpoints.
Credentials for the test mode are available here: [Connect Development Environment](https://github.com/vatsimnetwork/developer-info/wiki/Connect-Development-Environment).
=> Add VATSIM OAuth2 provider

src/Zalo/Provider.php
Zalo Login API v3 had already deprecated https://developers.zalo.me/docs/api/developer-notification/thong-bao-ngung-ho-tro-hoan-toan-dich-vu-zalo-login-v3-post-6905?campaign=DEVELOPER_BANNER_CAMPAIGN. Migrate to v4 so zalo provider can working again.
This is my first pull request. Please give feedback if have some problems.
Sorry for my bad English, English is not my first language.
=> Migrate from Zalo Login API v3  to V4

src/FusionAuth/Provider.php
Picture can also be null if no image is used in fusionauth. Currently if no avatar is set, this will break.
=> feat(fusionauth): picture can be null

src/StackExchange/README.md
Provider.php calls for keys site and key from the config. The key id different from the client_id and it needs both. When you go https://stackapps.com/apps/oauth/register it issues an Id, Key, and Secret.
Called from these lines:
* https://github.com/SocialiteProviders/Providers/blob/master/src/StackExchange/Provider.php#L80
* https://github.com/SocialiteProviders/Providers/blob/master/src/StackExchange/Provider.php#L82
Without it, it returns the array key `site` not found. Does the same for the `key`.
The site needs to be one of their providers: stackoverflow works.
=> Update StackExchange Readme with needed keys

src/Todoist/Provider.php
v8 was deprecated on December 5 2022 and doesn't work anymore.
I didn't notice any incompatibility, but here's the migration guide from v8: https://developer.todoist.com/sync/v9/#migrating-from-v8
=> Use Todoist's Sync API v9

src/Instagram/Provider.php, src/Instagram/README.md
Update work out the box the API calls in `getUserByToken` were calling deprecated methods.
=> Update Instagram provider to match Instagram api and work again.

src/Apple/Provider.php
Because `getUserByToken()` is a protected function, you cannot check an identity token directly from the Socialite driver. This PR intend to allow the verification of a JWT by a public function, returning a SocialiteUser, or throwing an InvalidStateException when the given JWT is incorrect
=> [Apple] Adding method to return SocialiteUser by JWT token

monorepo-builder.yml, src/GovBR/GovBRExtendSocialite.php, src/GovBR/Provider.php, src/GovBR/README.md, src/GovBR/composer.json
Provider for [GovBR](https://www.gov.br). 
TLDR;
Gov.br is a project to unify the digital channels of  brazil's federal government. 
It all starts with the gov.br portal, which brings together, in one place, services for citizens and information on the activities of all areas of government. By December 2020, the Government websites will be integrated, making the gov.br portal the single entry point to the institutional pages of the federal administration, offering citizens a direct and quick channel for relationship with federal agencies.
Developer docs: http://manual-roteiro-integracao-login-unico.servicos.gov.br/
=> add GovBR oauth2 provider

src/Saml2/Provider.php
Based on [this document](https://shibboleth.atlassian.net/wiki/spaces/CONCEPT/pages/948470554/SAMLKeysAndCertificates) KeyDescriptors without use tag should be used as both signing and encryption key. The official [metadata standard](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) also describes the use attribute as optional.
We already had to deal with such a configuration so this pull request allows the usage of such key descriptors.
Also requiring edit access for PR-s might not be the best as I had to fork it to my personal account since this feature is not supported on organisation repositories.
=> [Saml2] Allow combined keydescriptors for signing

src/Microsoft/Provider.php
Added ability to retrieve tenant information when using multi-tenant auth to allow for tenant filtering for any apps that may wish to form allow/blocklists or who may want to only allow access to "internal" tenants.
=> [Microsoft] Added ability to retrieve tenant information when using multi-tenant auth

src/Usos/README.md
Double backslashes has been replaced by single backslashes at EventServiceProvider example code
=> Documentation fix

src/Saml2/Provider.php
While working on a project I came across an issue with the Name ID Format not being a match with the IDP's. I believe this is a valuable addition to the library to extend the configuration and add the ability to configure the `SamlConstants::NAME_ID_FORMAT_PERSISTENT` being used in the Provider class.
By default the value will continue to be the default `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` value. But it also allows the developer to set a new config value (`sp_name_id_format`) which would then change the name format.
I added a getter method, `Provider::getNameIDFormat()`, which validates the configured name id, in case it is not valid, it returns the `SamlConstants::NAME_ID_FORMAT_PERSISTENT` by default. Then updated the two references to use the getter instead of the …
=> [Saml2] Configurable SAML2 Name ID Formats

src/TikTok/Provider.php
The code in master branch gets user details through `open-api.tiktok.com/oauth/userinfo` endpoint which now seems outdated as it is not even mentioned in the current version of official Tiktok API [documentation](https://developers.tiktok.com/doc). Also with this endpoint I've faced issues like 'Undefined array key "avatar_larger"'. 
Furthermore using of this endpoint leads to code inconsistency because with the API access token it requires also to send `open_id` field in `getUserByToken` method.
At the same time there is an official [user details endpoint](https://developers.tiktok.com/doc/tiktok-api-v2-get-user-info) which requires only access token. 
The fix switches getUserByToken method to this endpoint.
=> get Tiktok user from the official user details endpoint

src/TikTok/Provider.php
Seems like https://github.com/SocialiteProviders/Providers/pull/994 introduced a bug:
After updating I started getting this error:
```Undefined array key "open_id"```
Before using this new endpoint, the tiktok response was like:
```json
{
"data": {
"access_token": "act.c39724355c65afcd2d7026dcdbd76d40LJQ7fHsqvfUVmZl5nxWKEJ1FU1wc!6393",
"captcha": "",
"desc_url": "",
"description": "",
"error_code": 0,
"expires_in": 86400,
"log_id": "20220714041044010002007735002037040BAF34",
"open_id": "cdbbfaea-34f6-4a45-ab45-b12f78b1813d",
"refresh_expires_in": 31536000,
"refresh_token": "rft.dc8946222f5c87a21f681dc7995e3hEuMiySL8qLspsKgovFb6D0NyMly!6418",
"scope": "user.info.basic"
},
"message": "success"
}
```
But using the new endpoint, the user is nested under a `user` property:
```json
{
"data":{ …
```
=> fix: extracting Tiktok user from nested property

src/Keycloak/Provider.php, src/Keycloak/README.md
Added post logout redirect for Keycloak v18+ using either clientId or idTokenHint or both of them as one of them is required for post logout redirect to work.
Added the possibility to add additional parameters using a key value array.
Updated README.
@atymic
=> [KEYCLOAK] Added post logout redirect for Keycloak v18+

src/SuperOffice/Provider.php
Due to some upcoming updates in SuperOffice they require that the API endpoint URL is dynamic.
- https://community.superoffice.com/no/technical/forums/general-forums/announcements/currently-testing-in-sod-api-calls-must-now-use-the-tenants-correct-public-endpoint/
- https://community.superoffice.com/no/technical/forums/general-forums/announcements/breaking-changes-api-urls-for-online-tenants/
This will give some idea of what this additional request returns https://sod.superoffice.com/api/state/Cust12345.
Since this requires additional requests, cache has been added on an 8 hour interval. The cache name chosen matches that of another package I use https://gitlab.com/cadix/web/superoffice-api/-/blob/dev/src/Model.php#L329.
=> Updated SuperOffice provider

src/FusionAuth/Provider.php, src/FusionAuth/README.md
Minor changes to the FusionAuth provider:
- :alien: Checking for either `name` or `given_name`/`family_name` attributes when building `User` object (the API may return both)
- :necktie: Making `tenant_id` optional (you can leave it blank if you only have one)
- :pencil2: Fixing typo with the `::class` constant in the README file (it was missing one `:`)
=> [FusionAuth] Changing required properties and better handling API responses

src/Apple/AppleSignerInMemory.php, src/Apple/AppleSignerNone.php, src/Apple/Provider.php, src/Apple/composer.json
Add lcobucci/jwt 5.0 Support with fix #1015 .
=> Apple - lcobucci/jwt 5.0

src/Apple/Provider.php
This adds a first-party feature to refresh the access token using the previously acquired refresh token.
=> feat: add `refreshToken` to apple provider

src/Saml2/Provider.php
Currently if a status is unsuccessful, only the code is returned without the message.
The message is useful for correcting the issue.
=> SAML2 - Include message on unsuccessful status

src/Apple/Provider.php
This PR fixes the return type for Apple on the `userByIdentityToken()` method. 
`User` is already imported here:
https://github.com/SocialiteProviders/Providers/blob/c3e663e495f6db2a5191176803933ff6f193cde1/src/Apple/Provider.php#L20-L23
TypeError SocialiteProviders\Apple\Provider::userByIdentityToken(): Return value must be of type SocialiteProviders\Apple\SocialiteUser, SocialiteProviders\Manager\OAuth2\User returned
```
at vendor/socialiteproviders/apple/Provider.php:134
130▕     public function userByIdentityToken(string $token): SocialiteUser
131▕     {
132▕         $array = $this->getUserByToken($token);
133▕ 
➜ 134▕         return $this->mapUserToObject($array);
135▕     }
136▕ 
137▕     /**
138▕      * Verify Apple jwt.
```
=> Apple: Fix return type on `userByIdentityToken()`

src/TikTok/Provider.php
Tiktok has deprecated their v1 API endpoints and will not longer work after September 2023. This PR updates the TikTok provider accordingly to work with the v2.
Changes: 
- Added `Content-Type` to `application/x-www-form-urlencoded` to the token headers.
- Removed nested `data` property from user response.
- Replaced URLS to the new v2 endpoints.
- Add `redirect_uri` field to the token fields list as it's now required.
As of now, you only had to register "authorised" domains in the TikTok developer console to be able to redirect the user back to your app. In order to use the new endpoints you have to register the full redirect URL in your app settings just like in other providers.
This would require a new major release (V5) as developers have to make some changes in their TikTok app …
=> Tiktok – Upgrade tiktok API URLs to use v2 (v1 deprecating in Sep 2023)

src/Discord/Provider.php
With discord's new naming system, only displays the discriminator if the user has one.
=> On nickname discriminator is now displayed only if the user has assigned one

src/AzureADB2C/Provider.php, src/AzureADB2C/composer.json
The current version set in the composer file for AzureADB2C is incompatible with the current version of Laravel passport (requires 6.4 or higher).
=> Update firebase/php-jwt to latest version (6.8) 

src/FranceConnect/Provider.php
Do not use `array_add`. This helper function is not available any more with the Laravel framework.
=> Do not use array_add

src/Steam/Provider.php, src/Steam/README.md
I added this option because of my problem today - I deployed my application to production using a Docker container (I don't use HTTPS in the container, it's just a reverse proxy from HTTPS to the container) and I can't log in via Steam. I found the problem, solved it and created a pull request
=> Added force HTTPS config option for Steam provider

src/TikTok/Provider.php
The `union_id` field is supposed to act as a common user key shared across the apps of the same developer. Even if it's included in [TikTok's v2 docs](https://developers.tiktok.com/doc/tiktok-api-v2-get-user-info) and being requested to be included in the response when fetching the user [here](https://github.com/SocialiteProviders/TikTok/blob/master/Provider.php#L103), it is not always being provided in the response as the other fields. Still unclear why this is happening but happens. Since this parameter is required to construct the User instance, it fails.
This PR just fixes the cases where this field is not being included by setting it to `null`.
=> TikTok – fix: support mapping users without union_id

src/Authentik/Provider.php
Added ability to refreshToken to the Authentik provider based on https://github.com/SocialiteProviders/Providers/pull/1022/commits/07f607f9c0e73b18324faa609ae6aa9bb4e0062f.
=> Authentik: add refreshToken method

src/Authentik/Provider.php
I didn't consider that the AbstractProvider doesn't have a public method for this, so this fixes it.
=> Authentik: change method to public and fix return

src/Pr0gramm/Provider.php
The pr0gramm.com API returns the User ID in a field called `identifier`. This PR adds a mapping, so the ID can be accessed easily.
=> Use ID returned by pr0gramm.com

src/Saml2/Provider.php
I created this PR because today I needed SAML Single Logout from Service Providers (SP) to Microsoft ADFS, so I added logoutRequest method to Providers class and added chance to specify RelayState in SAML messageContext.
Tested with MS Azure AD, both directions: SLO from IDP to SP and SP to IDP. Worked.
Closes #978
=> Add SP initiated logoutRequest, add RelayState in messageContext

src/Admitad/Provider.php
According to the [AdmitAd scope documentation](https://developers.admitad.com/hc/en-us/articles/7930273820689-Help-on-access-settings):
> it is required to send `scope` parameter containing names of rights separated by space.
This change should fix this up so it is possible to use the Laravel `->setScopes()` function.
=> AdmitAd: use space as the scope separator

src/Saml2/Provider.php, src/Saml2/README.md
Replaced hard-coded value, now it's reading the sp_sign_assertions from the config key and setting the given value, default to true to avoid breaking changes.
=> Added support to read sp_sign_assertions key to remove hardcoded value

src/LaravelPassport/README.md
I spent quite a long time trying to troubleshoot an issue where the user object returned from the Laravel-Passport provider was coming through with all null attributes. After finally finding https://github.com/SocialiteProviders/Providers/issues/922, my problem was resolved.
This is technically mentioned in the [Passport docs](https://laravel.com/docs/10.x/passport#protecting-routes), but I never made the connection to how it would operate with Socialite. It makes sense now, but I feel it wasn't very clear.
I was hoping to contribute this small note in the docs here to hopefully save others from this.
Thanks!
=> Add note about Passport server route configuration

src/StreamElements/Provider.php
The payload response from the API has changed a bit and it appears StreamElements has changed their token type to "oAuth" on these types of requests. 
I used their javascript example to find the solution https://github.com/StreamElements/authentication-samples/blob/master/nodejs/index.js
This will resolve https://github.com/SocialiteProviders/Providers/issues/1003
=> [streamelements] Fix Authorization type and mapUserToObject

src/Discord/Provider.php, src/Discord/README.md
Discord supports transparency in avatars and using the JPEG format for them looks very ugly, so switch to PNG.
=> Fix bad-looking transparent Discord avatars

src/Apple/Provider.php
the refreshToken method signature does not match AbstractProvider which will result in a fatal error.
this PR sets the signature to match.
=> Fixes for Apple signature

src/AutodeskAPS/AutodeskAPSExtendSocialite.php, src/AutodeskAPS/Provider.php, src/AutodeskAPS/README.md, src/AutodeskAPS/composer.json
- Fixed naming;
- Added `region` as a config parameter;
- Fixed docs URL to match https://github.com/SocialiteProviders/website/pull/39;
Since the repository name is https://github.com/SocialiteProviders/AutodeskAPS, we might want to change the composer package name as well to something like `socialiteproviders/autodesk-aps`. The only 2 installs of the [package](https://packagist.org/packages/socialiteproviders/aps) at the moment are from me.
=> Autodesk APS fix naming and updated URLs

src/Okta/Provider.php
Fix signature for `Provider@getRefreshTokenResponse()` due to the same method name (with a different signature) being introduced by https://github.com/laravel/socialite/pull/675
see also: https://github.com/SocialiteProviders/Okta/pull/7
=> Fix Okta `Provider@getRefreshTokenResponse()` signature

src/Onelogin/Provider.php
Similar to https://github.com/SocialiteProviders/Providers/pull/1128, this fixes the signature for OneLogin (created by upstream change method added in https://github.com/laravel/socialite/pull/675)
=> Update OneLogin `Provider@getRefreshTokenResponse()`

src/Zendesk/README.md
Zendesk has a required 'subdomain' parameter which is not currently documented.
=> Add Subdomain explanation to Zendesk Provider

src/StartGg/Provider.php
The recently added `getRefreshTokenResponse()` method (https://github.com/laravel/socialite/pull/675) does not work with [start.gg](https://dev.start.gg/docs/oauth/oauth-overview#refresh-token) as they use an unconventional setup for updating refresh tokens.
This PR overrides `getRefreshTokenResponse()` with the necessary changes.
=> Fix Start.gg `getRefreshTokenResponse()`

monorepo-builder.yml, src/Indeed/IndeedExtendSocialite.php, src/Indeed/Provider.php, src/Indeed/README.md, src/Indeed/composer.json
Hi,
I am requesting to add indeed OAuth Provider, Here is the doc
https://docs.indeed.com/dev/docs/log-in-with-indeed
https://docs.indeed.com/dev/docs/upgrade-oauth
=> Add Indeed OAuth Provider

src/Orcid/Provider.php
In the event user data in the response from ORCID does not have a supplied name, an "array offset" error will be encountered because the `value` key won't exist as it's currently specified. 
"Family names" (or last names) are considered optional by ORCID, which means `$user['person']['name']['family-name']` won't always have a `['value']` key available.
For the moment, "given names" (or first names) are required by ORCID so there's no problem assuming this `['value']` information will exist in the response, but if ORCID ever does the right thing and makes "given names" optional, this will cause errors. It would be a good idea to future proof this with a null coalesce as well. My solution also reduces code duplication.
=> fix: Prevent null array offset errors in Provider.php for ORCID

monorepo-builder.yml, src/MercadoPago/MercadoPagoExtendSocialite.php, src/MercadoPago/Provider.php, src/MercadoPago/README.md, src/MercadoPago/composer.json
Very similar to existent MercadoLibre but it changes the auth URLs and it is focused on payments APIs.
Docs: https://www.mercadopago.com.br/developers/pt/reference/oauth/_oauth_token/post
=> feat: Add MercadoPago custom provider

monorepo-builder.yml, src/Clerk/ClerkExtendSocialite.php, src/Clerk/Provider.php, src/Clerk/README.md, src/Clerk/composer.json
Implements the provider for [Clerk](Clerk.com)
Their OAuth2 usage guide is found [here](https://clerk.com/docs/advanced-usage/clerk-idp)
Created the provider using the generator and used the Auth0 one as a guide
=> feat: implement Clerk provider

src/Clover/CloverExtendSocialite.php, src/Clover/Provider.php, src/Clover/README.md, src/Clover/composer.json
Followup to https://github.com/SocialiteProviders/Providers/pull/1157 including some suggestions from https://github.com/SocialiteProviders/Providers/pull/1162
=> finish Clover

src/Twitch/Provider.php
Refreshing tokens with Twitch will result in a TypeError. Socialite expects the scope to be returned as a `string`, but Twitch will return the scope in an `array`.
Use the scope array directly instead of using `explode()`.
```php
Socialite::driver('twitch')->refreshToken($refreshToken);
```
Example [response](https://dev.twitch.tv/docs/authentication/refresh-tokens/#how-to-use-a-refresh-token):
```json
{
"access_token": "1ssjqsqfy6bads1ws7m03gras79zfr",
"refresh_token": "eyJfMzUtNDU0OC4MWYwLTQ5MDY5ODY4NGNlMSJ9%asdfasdf=",
"scope": [
"channel:read:subscriptions",
"channel:manage:polls"
],
"token_type": "bearer"
}
```
Result:
```php
TypeError
explode(): Argument #2 ($string) must be of type string, array given
at vendor/laravel/socialite/src/Two/AbstractProvider.php:357
353▕         return …
```
=> Fix Twitch TypeError when refreshing tokens

src/InstagramBasic/Provider.php
Align the getCodeFields method with the AbstractProvider.php where the CodeFields are merged with the external parameters.
=> fix: instagram provider merge code fields

src/LifeScienceLogin/Provider.php
LSLogin v2 uses a new config URL now. Services can be self-managed via  https://services.aai.lifescience-ri.eu. Once you upgrade to the new provider version, you have to update the `LSLOGIN_CLIENT_ID` and `LSLOGIN_CLIENT_SECRET`, too.
=> Update LifeScienceLogin config URL

src/AzureADB2C/Provider.php
Azure ADB2C can return a `email` key. This PR checks if there is a `emails` array or a singel `email` key.
=> Update Azure ADB2C user email field

src/TikTok/Provider.php
In v2, `username` can be requested only if `user.info.profile` scope is set.
Instead of forcing the scope, since it's not even in the default list of scopes set in the provider, we could just add the username field if the scope is present.
Closes #1198
=> Make TikTok username optional based on scopes set

src/Microsoft/Provider.php
- Azure AD is being deprecated in favour of Microsoft Graph
- https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview
- This small PR just brings the logout functionality from `azure` over to `microsoft`
=> #1138 Bring logout from azure to microsoft

src/Auth0/Provider.php
Use Laravel's helper function `Arr::get` when accessing the 'email' key in the `$user` array. 
This prevents PHP from throwing an "Undefined index" error when trying to access the 'email' key that doesn't exist in the array. Valid in the case where the email is not a claim used to identify the user.
=> Add safe check for email claim

src/ClaveUnica/Provider.php
Acroding to official implementation guide of ClaveUnica, there is no email scope
Official guide:
https://claveunica.gob.cl/instituciones link "Ir a guía técnica"
Direct link:
https://docs.google.com/document/d/16c0D2jVhuYOYGI9z4kC2aoNH8oWNA9v1cc3tXQ76TO0/edit
=> ClaveUnica provider: set scopes acording to Implemetation guide

src/ClaveUnica/Provider.php
Fix url acording to official implementation guide.
Correct is: https://accounts.claveunica.gob.cl/openid/userinfo
Official documentation:  https://claveunica.gob.cl/instituciones button "Ir a la guía"
Direct link: https://docs.google.com/document/d/16c0D2jVhuYOYGI9z4kC2aoNH8oWNA9v1cc3tXQ76TO0/edit
=> ClaveUnica provider: fix url in getUserByToken

monorepo-builder.yml, src/Ivao/IvaoExtendSocialite.php, src/Ivao/Provider.php, src/Ivao/README.md, src/Ivao/composer.json
The OAuth endpoints for the IVAO API can be found [here](https://api.ivao.aero/.well-known/openid-configuration). This URL provides all the necessary information, including the authorization, token, and userinfo endpoints.
Since the endpoints for other providers are hard-coded in this repository, I have also hard-coded the IVAO endpoints. There is no reason to expect these endpoints to change, so this approach ensures stability.
For more details, you can refer to the [IVAO API documentation](https://api.ivao.aero/docs).
=> Add IVAO Provider

monorepo-builder.yml, src/Roblox/Provider.php, src/Roblox/README.md, src/Roblox/RobloxExtendSocialite.php, src/Roblox/composer.json
This commit introduces the Roblox OAuth2 Provider for Laravel Socialite. It includes the provider's installation and usage instructions in the README file as well as the implementation of the Provider class. It also updates the monorepo-builder.yml file to include a new reference to the Roblox provider repository.
=> Add Roblox OAuth2 Provider for Laravel Socialite

src/Vatsim/Provider.php, src/Vatsim/README.md
When using the VATSIM OAuth, the return values you have set now work, but in most applications, the developers of these sites are looking into more of the data that the OAuth API returns.
I have added all the most common items that are normally used by VATSIM OAuth users.
See VATSIM Documentation here: https://vatsim.dev/api/connect-api/get-user
If you have any questions, please let me know!
=> Update VATSIM API Request Info

src/UAEPass/Provider.php, src/UAEPass/README.md, src/UAEPass/UAEPassExtendSocialite.php, src/UAEPass/composer.json
This PR adds UAE Pass provider.
[Official UAEPass Website](https://uaepass.ae/about
)
=> Added UAEPass Provider

src/Fiken/FikenExtendSocialite.php, src/Fiken/Provider.php, src/Zettle/Provider.php, src/Zettle/ZettleExtendSocialite.php
Noticed that I bungled the filename/classname in the Fiken provider I made a few weeks ago. Then copying led to the same error in the Zettle provider that was just merged.
=> fix: fiken and zettle provider classnames

src/Atlassian/Provider.php
As stated in [Atlassian's documentation](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/#1--direct-the-user-to-the-authorization-url-to-get-an-authorization-code), scopes should be separated with a space.
Currently, the `scopeSeparator` property in `AbstractProvider` is set to a comma so this provider does not work.
=> Added scopeSeparator property to Atlassian provider

monorepo-builder.yml, src/Threads/Provider.php, src/Threads/README.md, src/Threads/ThreadsExtendSocialite.php, src/Threads/composer.json
This PR adds a provider for Threads (www.threads.net), the Twitter-like social network of Meta.
Note: Threads does not support refresh tokens, but allows the default short-lived access tokens to be exchanged for long-lived refreshable access tokens. I've added example code in the README.md instead of incorrectly implementing it in the `getRefreshTokenResponse` method.
Docs: https://developers.facebook.com/docs/threads
=> Add Threads provider

monorepo-builder.yml, src/Aikido/AikidoExtendSocialite.php, src/Aikido/Provider.php, src/Aikido/README.md, src/Aikido/composer.json
This PR adds support for Aikido's OAuth provider
https://apidocs.aikido.dev/ 
Aikido does not have a user endpoint, but have a workspace endpoint instead. An authentication is tied to the workspace, not to the specific user. 
Aikido is also one of the providers which uses `Basic` auth in the headers for client and secret for their token requests.
=> feat: add Aikido OAuth support

src/LaravelPassport/Provider.php
fixed https://github.com/SocialiteProviders/Providers/issues/1219
=> Make LaravelPassport userinfo_uri configurable.

src/Aikido/Provider.php
Adding back the Basic auth header for the token request which was removed as part of the reviewing process. 
Without it the following error will happen
```
Client error: `POST https://app.aikido.dev/api/oauth/token` resulted in a `401 Unauthorized` response:
{"error":"invalid_client","error_description":"The request is missing an Authorization header"}
```
=> fix: Aikido - add basic auth header for token request

src/AutodeskAPS/Provider.php
Fixing APS OAuth.
Also added possibility to use `setConfig`. This makes it possible to use the package in a multi-tenancy app. 
According to the [docs](https://aps.autodesk.com/en/docs/oauth/v2/tutorials/get-3-legged-token/#step-3-exchange-the-authorization-code-for-an-access-token) a base64 encrypted header of the client ID and secret is required. But not all "standard" headers are required or matched the docs. For example the content-type.
=> Fixing APS OAuth

src/Microsoft/Provider.php
I encountered an issue when using `include_tenant_info` where the tenant info being returned was null every time. The issue was caused by a forced use of the common tenant when fetching tenant info.
```php
$this->getConfig('tenant', 'common') === 'common'
```
I can't find a reason for why this was here, as it prevents users who are using a custom tenant ID or the `organizations` tenant from fetching tenant info. I can confirm tenant info began being returned again after removing the check. It still works with the `common` tenant, `organizations`  tenant, `consumers` tenant, and a custom `tenant identifier`.
In addition, when a user logs in with an account where the tenant does not exists (ex a personal account), Microsoft returns a 500 error. Currently, the exception being caught is a …
=> Fixes #1231; Null tenant info being returned. 

src/Slack/Provider.php
Slack does not allow you to use the legacy scopes for marketplace apps, so requesting the profile info fails marketplace review. This lets you zero out the scopes (getting using info fails, but the info is still abv on the access token response).
=> fix: slack set user scopes

src/AutodeskAPS/Provider.php, src/Cognito/Provider.php
No need to use `getConfig()` for `client_id`, `client_secret` and `redirect`
=> No need to use getConfig() for client_id and client_secret

src/AzureADB2C/Provider.php
Handle null values for 'nickname' and 'name' in AzureADB2C Provider
Updated the mapUserToObject method to handle empty/null values for 'nickname' and 'name' attributes when mapping user data.  This update ensures compatibility with Azure AD B2C tenants where these user attributes might not be provided or required.
=> handle user name empty values

src/LinkedIn/Provider.php
Since August 2023 LinkedIn [deprecated](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin) their older sign-in which is still used here. The new provider was added to Socialite so it should be used here.
#1115
=> Use LinkedIn sign in with Open ID 

src/Zendesk/Provider.php
Hi, I'm writing an integration for Zendesk that works globally, so I need to be able to change the subdomain dynamically. I extended the Provider but need to override this method 😄
=> Change the function visibility of Zendesk's getSubdomain

src/Steam/Provider.php
This pull request addresses an inconsistency in OpenID request responses observed between local development and AWS Lambda deployments. 
- **Normalization:** The code now normalizes OpenID request keys by consistently using the `openid.` previously it was sometimes `openid_` and other times`openid.` depending on where the code was executed. This ensures consistent handling across different environments.
- **Constant Definitions:** Introduced constants for common OpenID keys (`self::OPENID_RETURN_TO`, `self::OPENID_CLAIMED_ID`) to improve code readability, maintainability, and reduce the risk of typos.
- **Improved Error Handling:** Replaced the generic "unknown error" return with a more specific `OpenIDValidationException` when critical OpenID parameters are missing from the request, …
=> Fix: diffrent request resposne from diffrent hosts

src/Microsoft/Provider.php, src/Microsoft/composer.json
As per request for PR  in https://github.com/SocialiteProviders/Providers/issues/1029#issuecomment-1932034542
In the Microsoft provider we can skip any MS Graph API calls for Org/Tenant info  'https://graph.microsoft.com/v1.0/organization' when the user is identified as a consumer.
A new method `isConsumerTenant()` is used to verify and check the ID_TOKEN for tenant details via JWT decode.
> This essentially replaces the _catch_all_ try catch block (for failed API calls) used to determine tenant existence or not.
Inspired by AzureADB2C, XERO ( see  https://github.com/SocialiteProviders/Providers/blob/master/src/AzureADB2C/Provider.php#L168 )
----
1. Including 'openid' and 'profile' is the scope request allows the ID_TOKEN to be inspected and claims to be decoded.
* …
=> Microsoft provider - replace tenant api catch all when user is identified as a consumer type

monorepo-builder.yml, src/Authelia/AutheliaExtendSocialite.php, src/Authelia/Provider.php, src/Authelia/README.md, src/Authelia/composer.json
Add OAuth provider for https://www.authelia.com
Documentation: https://www.authelia.com/integration/openid-connect/introduction/
=> Add authelia provider

src/Steam/Provider.php
This code fixes error shown on image below.
This also was implemented in https://github.com/DoctorMcKay/node-steam-signin/commit/5cc818647f14e33981f3f09e2a405aad1787c684
=> fix(steam): add referer and origin http headers to steam provider because of 403 Forbidden HTTP error

src/Instagram/Provider.php
Meta changed the scope for Instagram from `user_profile` to `'instagram_business_basic'`, `'instagram_business_content_publish'`, `'instagram_business_manage_messages'`, and `'instagram_business_manage_comments'`. I tested it on my local machine, and it works fine with the new scope. Can you merge my proposed changes?
meta developer doc link for your reference
[Scope Update](https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login)
=> Update scopes For SSO Login

src/ClickUp/Provider.php
Changed base url from https://app.clickup.com/ to https://api.clickup.com/
=> Update ClickUp API URLs to use the new subdomain url

src/Twitter/README.md
Fix for compatibility issues with the latest socialite plugin and eliminating error "SocialiteProviders\Twitter\Provider does not extend Laravel\Socialite\Two\AbstractProvider"
Related topic for this issue and main discussion thread: SocialiteProviders/Providers#1193
=> Update README.md to fix compatibility issues

monorepo-builder.yml, src/Crowdin/CrowdinExtendSocialite.php, src/Crowdin/Provider.php, src/Crowdin/README.md, src/Crowdin/composer.json
Implemented by duplicating the Discord provider and following this service-specific guide: https://support.crowdin.com/developer/authorizing-oauth-apps/
The Crowdin OAuth API requires a scope to be specified, otherwise the authorization flow breaks. The list of available scopes is at https://support.crowdin.com/developer/understanding-scopes/ but there does not appear to be a generic "just the basic user info please" scope. "Translation status" (`project.status`) is one of, if not the least invasive from that list which also does not require an Enterprise license, that's why I opted to make it the default.
Side note: when using the default Laravel `php artisan serve` command, which uses `127.0.0.1:8000` as the host, authorization requests get mysteriously rejected with a 403 error by the …
=> feat: add Crowdin provider

src/Apple/README.md
This pull request includes a minor update to the `src/Apple/README.md` file. The change fixes the link to the Apple API Reference by correcting the URL format.
=> fix: sign in with apple docs URL

src/Apple/Provider.php
fixed 1354 by adding 2 seconds
=> [apple] Allow 3 seconds JWT leeway when verify.

src/Reddit/Provider.php
Three days ago Reddit silently broke authentication using the `ssl.reddit.com` subdomain (https://github.com/ReVanced/revanced-patches/issues/5387#issuecomment-3050530834), and right now, `www.reddit.com` should be used instead.
=> fix: Reddit provider

src/Discogs/Provider.php, src/Discogs/README.md
According to the [https://www.discogs.com/developers#page:authentication,header:authentication-oauth-flow](Discogs Documentation) passing in a user-agent as part of the OAuth flow is required. 
This allows a `user-agent` to be set in the config with a default fallback to `socialite-discogs`
=> Add User Agent Passing for Discogs

src/Azure/README.md
Change README to state the need to adjust **tenant_id** instead of **client_id** for multitenant realms.
=> Fix small documentation error for Azure Provider

src/GarminConnect/README.md
Fixes does not `extend Laravel\Socialite\Two\AbstractProvider` error by adding missing oauth1 Server class
=> Garmin Connect - Update README.md

monorepo-builder.yml, src/VKID/Provider.php, src/VKID/README.md, src/VKID/VKIDExtendSocialite.php, src/VKID/composer.json
New VK ID OAuth2 Provider
[OAuth VKontakte](https://github.com/SocialiteProviders/Providers/tree/master/src/VKontakte) now is deprecated.  
Obtaining a user access key (access token) is now possible only through OAuth VK ID.   
[VK ID Reference](https://id.vk.com/about/business/go/docs/ru/vkid/latest/oauth-vk#OAuth-VKontakte)
=> feat: VK ID OAuth2 Provider

monorepo-builder.yml, src/PocketID/PocketIDExtendSocialite.php, src/PocketID/Provider.php, src/PocketID/README.md, src/PocketID/composer.json
Homepage: https://pocket-id.org
Documentation: https://pocket-id.org/docs
=> Add PocketID provider

src/Clerk/Provider.php
Clerk does not provide avatars by default.
=> Handle null avatar in user data

src/Mailru/Provider.php
The "nickname" field, in a user object, is not always returned since it's a relatively new field. Therefore, old mail.ru accounts do not have that field and mail.ru OAuth does not return that field in their response.
This bug breaks mail.ru OAuth for older accounts and some users cannot register or login via Mailru Provider.
=> Fix for Mailru Provider
