SocialiteProviders/Providers

src/Uber/Provider.php

- The real issue was not solved. The scope should be sent as a string
but with "spaces" as separator.
Sorry about that, I thought that the "array way" was right, but then i've tried to add more scopes and I see that I was wrong.

Fix the Uber provider

---

src/QQ/composer.json

see 
https://github.com/apollopy/Providers/blob/master/src/QQ/Provider.php#L3
https://github.com/apollopy/Providers/blob/master/src/QQ/QqExtendSocialite.php#L3

[QQ] change namespace

---

src/SalesForce/Provider.php

possibility to use for sandboxes and production environments

[SalesForce] Added configable instance url

---

build/split.sh
src/Acclaim/AcclaimExtendSocialite.php
src/Acclaim/Provider.php
src/Acclaim/composer.json

Acclaim is a Badge management system for certified courses.

Accliam provider is added

---

src/Discord/Provider.php

ムjakeム - Jan 8th, 2017
@Shylor we don't use discordcdn.com anymore.

changed to the new cdn path

---

src/Dropbox/Provider.php

Forgot to check what it does if there is no avatar => $user['profile_photo_url'] does not exist so check if isset

Check if no dropbox avatar exists

---

src/Microsoft-Graph/Provider.php

Update default scopes (see SocialiteProviders/Microsoft-Graph#1)

Update default scopes (see SocialiteProviders/Microsoft-Graph#1)

---

src/Slack/Provider.php

Based on the [Slack API documentation](https://api.slack.com/web), when an API request fails the global boolean property `ok` is set to false. The request responds with a 200 OK response. As a result, an unsuccessful API request does not cause any exception to be thrown. This causes an undefined index error to occur when trying to fetch the user.
For example, doing `Socialite::driver('slack')->stateless()->user();` without a code, or with an invalid code, will cause the following error
```
ErrorException in Provider.php line 64:
Undefined index: user
```
However, when doing the same thing with the google driver, `Socialite::driver('google')->stateless()->user();` will throw the following exception.
```
ClientException in RequestException.php line 111:
Client error: `POST …
```

Throw guzzle client exception when slack api request fails

---

src/SciStarter/Provider.php

I forgot to add these elements initially.  My apologies.

get user nickname, first name, last name, and email

---

src/Slack/Provider.php

Getting user informations requires the `identity.*` scopes, however we might want to not add them to the scope list for various reasons.
Instead of throwing an exception on this error, we return an empty user.
This is a non-breaking changement.

[Slack] Handle properly "missing_scope" errors

---

src/Pinterest/Provider.php

$match[0] returns the full url, $match[1] returns the username.

Changed $nickname to proper match from array

---

build/split.sh
src/Unsplash/Provider.php
src/Unsplash/UnsplashExtendSocialite.php
src/Unsplash/composer.json

add Unsplash provider

---

build/split.sh
src/TVShowTime/Provider.php
src/TVShowTime/TVShowTimeExtendSocialite.php
src/TVShowTime/composer.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/socialiteproviders/providers/65)

Added TVShowTime Provider

---

.gitignore
.idea/vcs.xml
build/split.sh
src/Projectv/ProjectvExtendSocialite.php
src/Projectv/Provider.php
src/Projectv/composer.json

new Provider projectv

---

build/split.sh
src/QuickBooks/Provider.php
src/QuickBooks/QuickBooksExtendSocialite.php
src/QuickBooks/Server.php
src/QuickBooks/composer.json

Adds OAuth1 Socialite Provider for Intuit QuickBooks online
[Intuit documentation](https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000000_quickbooks_online_overview)

Add QuickBooks SocialiteProvider

---

src/Shopify/Provider.php

Should be `myshopify_domain` not `shopify_domain`.

Fixed key applied to `$user['nickname']`

---

src/Shopify/Provider.php

_on the correct repo this time ;)_

Add name & email to the $user object

---

src/Buffer/Provider.php
src/Disqus/Provider.php
src/Dribbble/Provider.php
src/Dropbox/Provider.php
src/Foursquare/Provider.php
src/GameWisp/Provider.php
src/Google-Plus/Provider.php
src/Hitbox/Provider.php
src/Jira/Provider.php
src/Jira/Server.php
src/LinkedIn/Provider.php
src/Meetup/Provider.php
src/Mixer/Provider.php
src/Patreon/Provider.php
src/ProjectV/Provider.php
src/SalesForce/Provider.php
src/SciStarter/Provider.php
src/Slack/Provider.php
src/Spotify/Provider.php
src/Steam/Provider.php
src/Trello/Server.php
src/Twitch/Provider.php
src/VKontakte/Provider.php
src/VersionOne/Provider.php
src/Weixin-Web/Provider.php
src/WordPress/Provider.php
src/Yahoo/Provider.php
src/Yandex/Provider.php

Always use `Arr::get`
As `array_get` is an application helper that does nothing more than calling `Arr::get`

Always use Arr::get.

---

src/Google-Plus/Provider.php
src/ProjectV/Provider.php

Simplify some get calls.

---

src/Untappd/Provider.php
src/Untappd/UntappdExtendSocialite.php
src/Untappd/composer.json

Hi!
I've just created Untappd provider. I think it will be helpful.

Added Untappd OAuth2 Provider

---

.gitignore
build/split.sh
src/ArcGIS/ArcGISExtendSocialite.php
src/ArcGIS/Provider.php
src/ArcGIS/composer.json

Inclusion of ArcGIS OAuth2 provider. Also allows for self hosted Protal for ArcGIS instances.

Add ArcGIS Provider

---

src/ArcGIS/Provider.php

Change Bearer Token to a token query parameter. Also set format to JSON

Fix for getUserByToken() in ArcGIS

---

src/Dataporten/Provider.php

@faustbrian Can you please merge this?

Just set all attributes provided by OAuth Server.

---

src/VKontakte/Provider.php

Now there is no way to get Expires in property for Vkontakte driver. This PR fix it

Add expires in to VK provider

---

src/Imgur/Provider.php

Adds another HTTP request to receive the email.

[Imgur] Added email fetching.

---

build/split.sh
src/Smashcast/Provider.php
src/Smashcast/SmashcastExtendSocialite.php
src/Smashcast/composer.json

Add smashcast provider (Hitbox no longer supported)

Add smashcast provider

---

src/Yahoo/Provider.php

Yahoo provides given name and family name which should be used as full name.

Added missing user full name

---

build/split.sh
src/Discogs/DiscogsExtendSocialite.php
src/Discogs/Provider.php
src/Discogs/Server.php
src/Discogs/composer.json

Added an OAuth1 provider for discogs.com.

Added Discogs provider

---

build/split.sh
src/Microsoft/MicrosoftExtendSocialite.php
src/Microsoft/Provider.php
src/Microsoft/composer.json

as discussed in #128
im not sure how the git subsplit works, so i didnt update that script.

added new Microsoft provider

---

src/Line/Provider.php

I have specified param and return without going to inheritdoc
[Related](https://github.com/SocialiteProviders/Line/pull/1)

Add Line Provider comments

---

src/LaravelPassport/Provider.php

custom user mapping

---

build/split.sh

Add Laravel Passport to split.sh

Add Laravel Passport to split.sh

---

src/VKontakte/Provider.php

Fix VK API changes

---

build/split.sh
src/Steem/Provider.php
src/Steem/SteemExtendSocialite.php
src/Steem/composer.json

Steem Connect API v2 provider implemented

Steem OAuth2 Provider for Laravel Socialite

---

build/split.sh
src/IFSP/IFSPExtendSocialite.php
src/IFSP/Provider.php
src/IFSP/composer.json

Add IFSP OAUTH

---

src/IFSP/composer.json

Fix composer.json

---

src/VKontakte/Provider.php

A little more information in case of any error is response

Exception on error in response

---

src/Twitch/Provider.php

Twitch has published a new api. The endpoints and the headers for authorization of the API have changed.
https://dev.twitch.tv/docs/authentication/#sending-user-access-and-app-access-tokens
https://dev.twitch.tv/docs/api/

Update to work with the new Twitch API

---

src/QQ/Provider.php

QQ platform allows multiple applications to share user information, and UnionID is used as the judgement of user uniqueness among different applications.
QQ document:http://wiki.connect.qq.com/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
Code from:https://github.com/overtrue/socialite/blob/master/src/Providers/QQProvider.php

support UnionId

---

build/split.sh
src/Microsoft-TeamService/composer.json
src/Microsoft-TeamService/src/Provider.php
src/Microsoft-TeamService/src/TeamServiceExtendSocialite.php

this **PR** , adds OAuth 2 [Microsoft Team Service integration](https://docs.microsoft.com/en-us/vsts/integrate/get-started/authentication/oauth?view=vsts)

Add Microsoft TeamService provider

---

src/Line/Provider.php

1. Update LINE API URLs
2. Add "space" scopeSeparator
3. Add default scopes
4. Add JWT and get user from JWT

Update API URL and JWT

---

build/split.sh
src/Mollie/MollieExtendSocialite.php
src/Mollie/Provider.php
src/Mollie/composer.json

[Mollie](https://www.mollie.com/en/) is a Dutch Payment Provider which support the most common [payment-methods in Europe](https://www.mollie.com/en/).
You can use the [Mollie Connect-service](https://docs.mollie.com/oauth/overview) to access other merchants’ accounts with their consent, without having to exchange API keys

Add Mollie Payment Provider

---

src/Kakao/KakaoProvider.php

1. Chang api url to v2
2. Check keys exist
3. Check email is valid or verified
reference:
- https://developers.kakao.com/docs/restapi/user-management
- https://devtalk.kakao.com/t/v2-api/51366/2

Change url to v2 and check keys exist

---

src/GitLab/Provider.php

reference this [Previous PR](https://github.com/SocialiteProviders/GitLab/pull/4)

Upgrade Gitlab api version

---

src/Line/Provider.php

The following bugs have been fixed.
- use of exception is insufficient
- not support to base64url

fix line provider error

---

build/split.sh
src/UFS/Provider.php
src/UFS/UFSExtendSocialite.php
src/UFS/composer.json

This PR makes possible to authenticate users using OAuth 2 and API Sistemas provided by UFS (Universidade Federal de Sergipe).
Cheers.

Added provider for Universidade Federal de Sergipe (UFS)

---

src/VKontakte/Provider.php

VKontakte provider now returns the 'email' field

---

build/split.sh
src/UCL/Provider.php
src/UCL/UCLExtendSocialite.php
src/UCL/composer.json

API documentation: https://uclapi.com/docs/#oauth
Docs PR created: https://github.com/SocialiteProviders/Documentation/pull/14

UCL API provider

---

build/split.sh
src/Aweber/AweberExtendSocialite.php
src/Aweber/Provider.php
src/Aweber/Server.php
src/Aweber/composer.json

Aweber provider

---

build/split.sh
src/Orcid/OrcidExtendSocialite.php
src/Orcid/Provider.php
src/Orcid/composer.json

PR for [ORCID](https://www.orcid.org/)  oAuth Provider.

oAuth Provider for ORCID

---

src/Naver/NaverProvider.php

fixed notice error. The email and name fields may not be approved by naver.

fixed Naver mapUserToObject

---

build/split.sh
src/Teamleader/Provider.php
src/Teamleader/TeamleaderExtendSocialite.php
src/Teamleader/composer.json

Here you can find this service: [https://www.teamleader.eu](https://www.teamleader.eu)

Added Teamleader socialite provider

---

build/split.sh
src/Snapchat/Provider.php
src/Snapchat/SnapchatExtendSocialite.php
src/Snapchat/composer.json

The documentation which has been used located here https://docs.snapchat.com/docs/login-kit/

Add Snapchat oAuth2 Provider

---

build/split.sh
src/OSChina/composer.json
src/OSChina/src/OSChinaExtendSocialite.php
src/OSChina/src/Provider.php

I follow the [contribute documentation](https://socialiteproviders.netlify.com/contribute.html).
Generate code templates from the [generator](https://github.com/SocialiteProviders/Generators).
But it is different from other Providers: Such as `src` directory.
Should I share code through a separate project? 
Just like: [Weixin](https://github.com/SocialiteProviders/Weixin)

Added OSChina oAuth2 Provider 

---

.gitignore
src/Weixin/Provider.php

can't throw a friendly error when the code is invalid.

throw a friendly error where the code is invalid.

---

build/split.sh
src/GitHub/GitHubExtendSocialite.php
src/GitHub/Provider.php
src/GitHub/composer.json

This PR just adds `ConfigTrait` to the GitHub driver.

Make [GitHub] driver configurable

---

build/split.sh
src/Bitbucket/BitbucketExtendSocialite.php
src/Bitbucket/Provider.php
src/Bitbucket/composer.json

This PR just adds `ConfigTrait` to the Bitbucket driver.

Make [Bitbucket] driver configurable

---

src/Aweber/AweberExtendSocialite.php
src/Aweber/Provider.php
src/Aweber/Server.php
src/Aweber/composer.json

It was broken because off `App` prefix.

Fix [Aweber] driver namespace

---

src/MakerLog/Provider.php
src/MakerLog/composer.json

Hey @m1guelpf 
here the PR fixing two more issues on the makerlog provider. Let me know if you need any more changes.
-- Peter

FIX: adding required trailing slash and required minimum scope.

---

src/Google-Plus/Provider.php

Needs to activate Google People API (in Google console)

Replace Plus API with People API due Plus shutdown

---

build/split.sh
src/GarminConnect/GarminConnectExtendSocialite.php
src/GarminConnect/Provider.php
src/GarminConnect/Server.php
src/GarminConnect/composer.json

More information: http://developer.garmin.com/garmin-connect-api/overview/

Add Garmin Connect OAuth1 Provider

---

src/WeChatWeb/Provider.php
src/WeChatWeb/WeChatWebExtendSocialite.php
src/WeChatWeb/composer.json

WeChat Web Login, support: unionId and openid.
docs:
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316518&lang=en_US

Added WeChat Web OAuth2 provider

---

src/WeChatServiceAccount/Provider.php
src/WeChatServiceAccount/WeChatServiceAccountExtendSocialite.php
src/WeChatServiceAccount/composer.json

WeChat service account login docs:
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318259&token=&lang=en_US
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842

Added WeChat Service Account Provider

---

build/split.sh
src/SURFconext/Provider.php
src/SURFconext/SURFconextExtendSocialite.php
src/SURFconext/composer.json

https://wiki.surfnet.nl/display/surfconextdev/OpenID+Connect+authentication+flow

added SURFconext driver

---

build/split.sh
src/PeeringDB/PeeringDBExtendSocialite.php
src/PeeringDB/Provider.php
src/PeeringDB/composer.json

Details: https://docs.peeringdb.com/oauth/

Add PeeringDB

---

build/split.sh
src/OAuthgen/OAuthgenExtendSocialite.php
src/OAuthgen/Provider.php
src/OAuthgen/composer.json

provider for OAuthgen authentication provider [Docs PR](https://github.com/SocialiteProviders/Documentation/pull/54)

OAuthgen authentication provider

---

build/split.sh
src/MoiKrug/MoiKrugExtendSocialite.php
src/MoiKrug/Provider.php
src/MoiKrug/composer.json

Added moikrug.ru oAuth 2.0 provider.
Docs (ru): https://moikrug.ru/info/api

Added moikrug.ru oAuth2 provider

---

build/split.sh
src/Mailru/MailruExtendSocialite.php
src/Mailru/Provider.php
src/Mailru/composer.json

Hi, 
added mail.ru oAuth 2.0 provider.
Docs (ru): https://o2.mail.ru/docs

Added mail.ru oAuth2 provider 

---

src/Reddit/Provider.php

Reddit has avatars now. Who knew?

Added avatar to Reddit provider

---

build/split.sh
src/HeadHunter/HeadHunterExtendSocialite.php
src/HeadHunter/Provider.php
src/HeadHunter/composer.json

Added hh.ru oAuth 2.0 provider.
Docs (ru): https://github.com/hhru/api

Added hh.ru provider

---

build/split.sh
src/Zoho/Provider.php
src/Zoho/ZohoExtendSocialite.php
src/Zoho/composer.json

Hello, 
We have added **zoho.com** oAuth 2.0 provider.
Docs: https://www.zoho.com/accounts/protocol/oauth.html

Added Zoho oAuth2 provider 

---

src/Twitter/Server.php

Fixes #353
Use the https profile image instead of the http image for twitter

Use profile_image_url_https instead of profile_image_url for twitter user

---

src/OSChina/composer.json

Update: Providers/OSChina composer.json request

---

src/Bit.ly/Provider.php

Add:
- Email field
- Grant_type
Remove:
- [Profile Image](https://github.com/SocialiteProviders/Providers/blob/b33270a1b9a935970f76771e0f46d7e4a00411f8/src/Bit.ly/Provider.php#L53)

Fix Bitly: Retrieve a User with API V4

---

src/Coinbase/Provider.php

The Coinbase API received some changes over the last weeks and months which broke this provider.
- Their scopes have changed
- The data structure that represents a user has changed

fix coinbase scopes and user construction

---

src/WeChatServiceAccount/Provider.php

fix https://github.com/laravel-socialite-providers/socialite-providers/issues/10

HACK: snsapi_base overwrite snsapi_userinfo.

---

src/WeChatServiceAccount/Provider.php
src/WeChatWeb/Provider.php

@apollopy need userFromToken
```
$user = Socialite::driver('wechat_web')->userFromToken($token);
```
sinkcup/sinkcup.github.io#12

feat: wechat userFromToken

---

composer.json
monorepo-builder.yml
src/Keycloak/KeycloakExtendSocialite.php
src/Keycloak/Provider.php
src/Keycloak/composer.json

Keycloak.com is an open source Identity and Access Management solution aimed at modern applications and services.
https://github.com/keycloak/keycloak

Add keycloak provider

---

src/Zalo/Provider.php
src/Zalo/ZaloExtendSocialite.php
src/Zalo/composer.json

Zalo provider. Full docs [https://developers.zalo.me](https://developers.zalo.me)

add provider ZALO - https://developers.zalo.me

---

.editorconfig
.gitattributes

Add a .editorconfig file.

---

src/Wonderlist/Provider.php
src/Wonderlist/WonderlistExtendSocialite.php

fix: deprecate wunderlist

---

src/Goodreads/Provider.php

Need to test this actually solves the issue.
Closes #196

fix: skip verifier for goodreads

---

src/Steam/Provider.php
src/Steam/composer.json

WIP. Need to test. Anyone using this who's got a app setup, would be awesome if you could help with testing :)
New version drops all dependencies :) 
Closes #383

feat: re implement steam provider

---

src/Xero/Provider.php
src/Xero/XeroExtendSocialite.php
src/Xero/composer.json

As per
https://developer.xero.com/documentation/oauth2/overview

Add Xero OAuth2 Provider

---

monorepo-builder.yml
src/Procore/ProcoreExtendSocialite.php
src/Procore/Provider.php
src/Procore/composer.json

Adds a service provider for Procore, a construction management SaaS.

Adds Procore provider

---

src/Zoho/Provider.php

Fix #448 
- Adds email field 
- Updates name field to use full name.

Fix issue #448

---

src/Flexkids/Provider.php
src/Jira/RsaSha1Signature.php
src/Mattermost/Provider.php
src/Yiban/Provider.php

This PR remove useless variables;
there is no point declaring a variable, just to return it.

Remove useless variables.

---

src/Orcid/Provider.php
src/Yahoo/Provider.php

This PR remove duplicate methods.
Those methods don't do anything different from the ones declared in the parent class.

Remove duplicate methods.

---

src/Discogs/Provider.php
src/GarminConnect/Provider.php
src/Jira/RsaSha1Signature.php
src/Jira/Server.php
src/Mattermost/Provider.php
src/MediaCube/Provider.php
src/Opskins/Provider.php
src/Rdio/Server.php
src/VKontakte/Provider.php

Add missing imports.

---

src/Jira/Provider.php

Remove unrecheable return.

---

src/Apple/Provider.php
src/Coinbase/Provider.php
src/Flexkids/Provider.php
src/Jira/RsaSha1Signature.php
src/QuickBooks/Provider.php
src/SciStarter/Provider.php

This PR remove already interfaces that are already implemented in the abstracted classes.

Remove already implemented interfaces.

---

src/Tumblr/TumblrExtendSocialite.php

This PR removes unnecessary qualifiers.

Remove unnecessary qualifier

---

.gitattributes

This PR cleans up and update `.gitattributes` file.
Some files don't exist anymore, line ending setting was not set, etc...

Cleanup and update .gitattributes file.

---

src/Apple/Provider.php
src/FranceConnect/Provider.php
src/GarminConnect/Server.php
src/Gitee/Provider.php
src/IFSP/Provider.php
src/Jira/RsaSha1Signature.php
src/Orcid/Provider.php
src/Rdio/Server.php
src/Twitter/Server.php
src/WeChatServiceAccount/Provider.php
src/WeChatWeb/Provider.php
src/Weixin/Provider.php

Always prefer stricter comparisons

Always prefer stricter comparisons

---

src/Apple/Provider.php
src/Battlenet/Provider.php
src/Bitly/Provider.php
src/Dataporten/Provider.php
src/Faceit/Provider.php
src/Flexkids/Provider.php
src/GameWisp/Provider.php
src/GettyImages/Provider.php
src/GitLab/Provider.php
src/Instagram/Provider.php
src/Kakao/KakaoProvider.php
src/Line/Provider.php
src/Mattermost/Provider.php
src/OAuthgen/Provider.php
src/Procore/Provider.php
src/Shopify/Provider.php
src/Slack/Provider.php
src/StackExchange/Provider.php
src/Steam/Provider.php
src/Steem/Provider.php
src/Twitter/Server.php
src/Ufutx/Provider.php
src/VKontakte/Provider.php
src/WordPress/Provider.php
src/Xero/Provider.php

it is valuable to do a code clean up before the next big release.
This PR is the first of a small batch.
This code cleanup does the following:
- Remove useless imports.
- Modernize list syntax, and use single variables.
- Use camelCase names for variables.
- Remove unused parameters.
- Remove useless variables.
- Remove useless properties.

Code cleanup

---

src/Apple/composer.json
src/Jira/composer.json
src/Naver/composer.json

Add missing PHP extensions

---

src/Acclaim/README.md
src/Admitad/README.md
src/Apple/README.md
src/Asana/README.md
src/Aweber/README.md
src/Battlenet/README.md
src/Bitbucket/README.md
src/Bitly/README.md
src/Box/README.md
src/Buffer/README.md

Added api references
Added Buffer warning about closes new developers registration

feat(docs): Api references

---

monorepo-builder.yml
src/Whmcs/Provider.php
src/Whmcs/README.md
src/Whmcs/WhmcsExtendSocialite.php
src/Whmcs/composer.json

Add WHMCS OAuth2 provider

---

src/Whmcs/Provider.php

WHMCS doc link

---

monorepo-builder.yml
src/Binance/BinanceExtendSocialite.php
src/Binance/Provider.php
src/Binance/README.md
src/Binance/composer.json

Added Binance as a Provider. 
SocialiteProviders documentation PR: https://github.com/SocialiteProviders/website/pull/4

Added Binance Provider

---

monorepo-builder.yml
src/StreamElements/Provider.php
src/StreamElements/README.md
src/StreamElements/StreamElementsExtendSocialite.php
src/StreamElements/composer.json

Add StreamElements Provider

---

src/StreamElements/Provider.php
src/Streamlabs/Provider.php

Remove useless overrides

---

monorepo-builder.yml
src/Pixnet/PixnetExtendSocialite.php
src/Pixnet/Provider.php
src/Pixnet/README.md
src/Pixnet/composer.json

This PR add a driver for pixnet (https://www.pixnet.net). Pixnet is a blog platform in Taiwan.
API Documentations: https://developer.pixnet.pro/

add pixnet provider

---

src/Whmcs/Provider.php

Add required scopes (openid email profile)

Add Required Scopes

---

src/Streamlabs/Provider.php

Add scope separator to allow multiple scopes.

chore(streamlabs): add scope seperator

---

.github/workflows/subtree-pr-close.yml
tools/close-subtree-prs.php

feat: bot to close subtree PRs

---

src/HubSpot/Provider.php

Refer to: 
https://github.com/SocialiteProviders/Providers/issues/408
https://github.com/SocialiteProviders/HubSpot/pull/1

Correct hubspot provider scope separator to whitespace

---

src/Apple/Provider.php

fix: use guzzle instead of file_ in apple provider

---

src/Apple/Provider.php

$value is not a json string but a apple user id string and in that case json_decode will return null, so a check is needed

fix issue: array_key_exists null given

---

src/StreamElements/Provider.php
src/StreamElements/README.md

Added fields to user:
- ``alias``
- ``type``
- ``verified``
- ``partner``
- ``suspended``
Documentation: https://docs.streamelements.com/reference/channels#get-user-channel-details

feat(streamelements): add user fields

---

src/Telegram/Provider.php

fix(telegram): error when missing field

---

src/Steam/Provider.php
src/Steam/README.md

It needs to be merged to the latest release version which is 3.0.2
More info is in this issue #562

Steam Provider - fix config key and problem with userFromToken()

---

src/Steam/Provider.php

More info is in this issue #562

Steam Provider - always use http #562

---

src/YouTube/Provider.php
src/YouTube/README.md

Fix undefined index error when user doesn't have a channel.
Closes #394

fix: youtube no channel error

---

src/Okta/Provider.php
src/YouTube/README.md

Adding support for Okta custom authorization server as described in this PR: https://github.com/SocialiteProviders/Okta/pull/2

add okta custom auth server

---

src/MercadoLibre/MercadoLibreExtendSocialite.php
src/MercadoLibre/Provider.php
src/MercadoLibre/README.md
src/MercadoLibre/composer.json

This PR adds support for [MercadoLibre](http://mercadolibre.com/), an eCommerce platform from Argentina that has presence in 18 Latin American countries.
Hope the platform (and this PR) meets the requirements!

Add MercadoLibre provider

---

src/Fitbit/Provider.php

fix: guzzle 7 bug

---

src/SURFconext/Provider.php

This is actually my bad @atymic. Made a small typo while working from a different PC.
EDIT: Also check your Twitter DM 😉

[SURFconext] Fix typo in URL

---

src/Graph/Provider.php

Allow changing the /me endpoint to a different version.
e.g. "beta"

Added user_endpoint_version Config Key

---

src/Twitter/README.md

Twitter changed their settings and extra steps are necessary to enable Sign in With Twitter.

Update Twitter docs

---

monorepo-builder.yml
src/Monzo/MonzoExtendSocialite.php
src/Monzo/Provider.php
src/Monzo/README.md
src/Monzo/composer.json

Added Monzo Provider

---

src/Apple/Provider.php
src/Apple/composer.json

Fix AppleProvider issues #587 #529

---

src/Discord/Provider.php
src/Discord/README.md

Thought it would be a good idea to allow some choice for the avatar being received as discord offer a large range.
[Discord Docs](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints)
Not sure if I am doing this contribution correctly but didnt see anything on the docs about doing updates 😛

Added options for discord avatars

---

src/Apple/Provider.php
src/Apple/README.md
src/Apple/composer.json

At previous PR I only tested the stateless mode. The stateful mode will throw `InvalidStateException` I have fixed this issue on  This PR.

Fix AppleProvider throw InvalidStateException

---

src/Keycloak/README.md

Hello,
These values were not documented and the readme instructions were confusing.
Nothing more to say...

Documented `base_url` and `realms` configuration parameters

---

src/Nextcloud/NextcloudExtendSocialite.php
src/Nextcloud/Provider.php
src/Nextcloud/README.md
src/Nextcloud/composer.json

Nextcloud OAuth2

---

src/Battlenet/Provider.php

This creates the necessary conditionals to support the Chinese region.
Find the details here: https://develop.battle.net/documentation/guides/using-oauth

Introduce support for Chinese Battle.net accounts

---

monorepo-builder.yml
src/Adobe/AdobeExtendSocialite.php
src/Adobe/Provider.php
src/Adobe/README.md
src/Adobe/composer.json

This PR merges a brand new provider, Adobe.

Adobe Provider

---

src/Faceit/Provider.php
src/Steem/Provider.php
src/Teamweek/Provider.php
src/Yiban/Provider.php

Remove useless check.
`guzzlehttp/guzzle` is always installed with V6

Remove useless check.

---

src/Flexmls/Provider.php
src/Gitea/Provider.php
src/Gumroad/Provider.php
src/MercadoLibre/Provider.php
src/Monzo/Provider.php
src/Telegram/Provider.php

Stay consistent and always declare constant visibility.

Always declare constant visibility.

---

src/Battlenet/Provider.php

Always prefer stricter comparison.

Always prefer stricter comparison.

---

src/Discord/Provider.php
src/Faceit/Provider.php
src/IFSP/Provider.php
src/OAuthgen/Provider.php
src/ProductHunt/Provider.php
src/QQ/Provider.php
src/Spotify/Provider.php
src/Unsplash/Provider.php
src/VKontakte/Provider.php
src/WeChatServiceAccount/Provider.php
src/WeChatWeb/Provider.php
src/Weixin/Provider.php

Many conditions can be simplified by using the null coalescing operator

Use null coalescing operator.

---

.gitattributes

It is useless to export the `tools` folder.

Do not export tools folder.

---

src/Adobe/Provider.php
src/FranceConnect/Provider.php
src/Jira/Server.php
src/Orcid/Provider.php
src/VersionOne/Provider.php

Add a lot of missing imports 😔

Add a lot of missing imports.

---

composer.json

This PR ensures that packages are always sorted.

Ensure that packages are always sorted.

---

.github/workflows/test.yml

This PR removes the deprecated `--no-suggest` option.

Remove deprecated no-suggest option.

---

src/Notion/README.md

Add notion docs

---

src/Stripe/Provider.php
src/Stripe/README.md

Fixes https://github.com/SocialiteProviders/Providers/issues/681 - missing "email" in account API response.

Fix Stripe "email" error

---

src/Google/Provider.php

This PR simplifies the Google provider.

Simplify google provider.

---

composer.json
src/Amazon/composer.json
src/Apple/composer.json
src/ClaveUnica/composer.json
src/Fablabs/composer.json
src/Flexkids/composer.json
src/Flexmls/composer.json
src/GarminConnect/composer.json
src/Gitea/composer.json
src/Gumroad/composer.json
src/HabrCareer/composer.json
src/Mailru/composer.json
src/MediaCube/composer.json
src/Monzo/composer.json
src/Netlify/composer.json
src/OAuthgen/composer.json
src/PeeringDB/composer.json
src/QuickBooks/composer.json
src/SuperOffice/composer.json
src/Telegram/composer.json
src/UCL/composer.json
src/WeChatServiceAccount/composer.json
src/WeChatWeb/composer.json
src/Xero/composer.json
src/Zoho/composer.json

[Normalize](https://github.com/ergebnis/composer-normalize) all composer.json files.

Normalize all composer.json files.

---

src/Keycloak/Provider.php
src/Keycloak/README.md

Closes #625 
Needs major vers bump.

fix: default openid scope for keycloak

---

.github/workflows/test.yml
composer.json
src/Adobe/Provider.php

Lint the PHP code for all the versions of PHP
This is very required as we have no tests running for this repository.

Lint the PHP code

---

src/ConstantContact/Provider.php

Constant Contact changed all their endpoints for version 3 of the API so this fixes that.

Update Constant Contact to use V3 endpoints and scopes

---

src/Notion/NotionExtendSocialite.php

This PR fixes an incorrect namespace for the Notion provider.

Fix incorrect Notion namespace

---

src/Eveonline/Provider.php

This PR fixes lots of inconsistencies and issues with EveOnline provider that was introduced in https://github.com/SocialiteProviders/Providers/pull/691
---
See the commits for more details.

Eve online

---

src/Atlassian/composer.json
src/Eveonline/composer.json
src/Saml2/composer.json

Normalize come `composer.json` files that have been recently added/updated.

Normalize composer files

---

.github/workflows/test.yml
src/Rekono/Provider.php

- Use a validate flag in the workflow.
- Cache composer dependencies
---
The goal is to get the workflow ready to make some extra check ( code analysis, etc... )

Optimize workflow

---

src/Azure/Provider.php
src/Discord/Provider.php
src/Eveonline/Provider.php
src/FranceConnect/Provider.php
src/HeadHunter/Provider.php
src/Jira/Provider.php
src/Keycloak/Provider.php
src/Mattermost/Provider.php
src/MercadoLibre/Provider.php
src/Microsoft/Provider.php
src/Notion/Provider.php
src/Ovh/Provider.php
src/QuickBooks/Provider.php
src/SURFconext/Provider.php
src/SalesForce/Provider.php
src/Saml2/Provider.php
src/StackExchange/Provider.php
src/Steam/Provider.php
src/SuperOffice/Provider.php
src/TeamService/Provider.php
src/Telegram/Provider.php
src/Todoist/Provider.php
src/Trakt/Provider.php
src/WeixinWeb/Provider.php
src/Whmcs/Provider.php
src/Zendesk/Provider.php

Enforce consistancy for configuration access.
We shall always use getConfig for the keys which are related to the service.

Consistant configuration access.

---

src/TikTok/Provider.php
src/TikTok/README.md
src/TikTok/TikTokExtendSocialite.php
src/TikTok/composer.json

Added a [TikTok Login Kit](https://developers.tiktok.com/doc/login-kit-web) provider.

Added TikTok provider

---

src/Mattermost/Provider.php
src/TikTok/Provider.php
src/Whmcs/Provider.php

Remove some useless variables

---

monorepo-builder.yml
src/Neto/NetoExtendSocialite.php
src/Neto/Provider.php
src/Neto/README.md
src/Neto/composer.json

Neto Provider

---

src/Neto/Provider.php
src/Neto/README.md

fix: neto provider updates

---

src/Saml2/Provider.php
src/Saml2/README.md

Ref https://github.com/SocialiteProviders/Providers/issues/705

Saml2 - Custom Service Entity Id

---

.github/workflows/test.yml

Start testing php 8.1 with `fail-fast`.

Start testing php 8.1 with fail-fast.

---

src/Apple/Provider.php

Fix depreciation notice.

---

src/Neto/composer.json
src/TikTok/composer.json

Normalize some composer files.

Normalize some composer files.

---

.github/workflows/test.yml

Fix CI cache key.

---

src/Atlassian/Provider.php
src/Saml2/Provider.php

Declare the constant visibility.

Declare the constant visibility.

---

monorepo-builder.yml
src/Webex/Provider.php
src/Webex/README.md
src/Webex/WebexExtendSocialite.php
src/Webex/composer.json

Webex API docs/tutorials:
- https://developer.webex.com/docs/integrations
- https://developer.webex.com/blog/real-world-walkthrough-of-building-an-oauth-webex-integration

Add Webex provider

---

monorepo-builder.yml
src/Lichess/LichessExtendSocialite.php
src/Lichess/Provider.php
src/Lichess/README.md
src/Lichess/composer.json

The authorization code flow with PKCE that allows users to login with Lichess. [https://lichess.org/api#tag/OAuth](url)

Add Lichess OAuth

---

monorepo-builder.yml
src/Cognito/CognitoExtendSocialite.php
src/Cognito/Provider.php
src/Cognito/README.md
src/Cognito/composer.json

Adding support for AWS Cognito OAuth2 connections.
Includes support for logging out of Cognito.

Add Cognito

---

.github/workflows/monorepo-split.yml
.github/workflows/subtree-pr-close.yml
.github/workflows/test.yml

Some workflows cleanup
Also :
- upgrade to `actions/checkout@v2` and `shivammathur/setup-php@v2`
- use PHP 8 for splitting the monorepo and closing the PRs

Some workflows cleanup

---

src/AzureADB2C/composer.json

Ensure that all `composer.json` files are normalized.

Ensure that all composer.json files are normalized.

---

src/Telegram/README.md

Method getScript() doesn't exist.

Method getScript() doesn't exist.

---

src/AzureADB2C/README.md

fix for https://github.com/SocialiteProviders/Providers/issues/769

clarify how to adjust the user mapping

---

src/Azure/Provider.php
src/Azure/README.md

- Remove the logout_url option from the config file
- Add getLogoutUrl method

Add getLogoutUrl for Azure provider

---

monorepo-builder.yml
src/MusicBrainz/MusicBrainzExtendSocialite.php
src/MusicBrainz/Provider.php
src/MusicBrainz/README.md
src/MusicBrainz/composer.json

[MusicBrainz](https://musicbrainz.org/) is an open music encyclopedia that collects music metadata and makes it available to the public.
https://musicbrainz.org/doc/Development/OAuth2

Add MusicBrainz Provider

---

src/Azure/Provider.php

Include the Proxy also for the Graph API. 
Not only the Login Request.

Update Azure Provider. Use the Proxy Param also for the Azure Graph API

---

monorepo-builder.yml
src/TwitCasting/Provider.php
src/TwitCasting/README.md
src/TwitCasting/TwitCastingExtendSocialite.php
src/TwitCasting/composer.json

[TwitCasting](https://twitcasting.tv) is one of the most popular livestreaming services in Japan.
API Reference: https://apiv2-doc.twitcasting.tv (Written in Japanese)
API Registration: https://en.twitcasting.tv/indexapi.php
🙏

Add TwitCasting Provider

---

monorepo-builder.yml
src/OpenStreetMap/OpenStreetMapExtendSocialite.php
src/OpenStreetMap/Provider.php
src/OpenStreetMap/README.md
src/OpenStreetMap/composer.json

OAuth2 Provider for OpenStreetMap
https://wiki.openstreetmap.org/wiki/OAuth

Add OpenStreetMap Provider

---

monorepo-builder.yml
src/Monday/MondayExtendSocialite.php
src/Monday/Provider.php
src/Monday/README.md
src/Monday/composer.json

Add Socialite provider for Monday:
https://apps.developer.monday.com/docs/oauth

Add Monday provider

---

monorepo-builder.yml
src/Mediawiki/MediawikiExtendSocialite.php
src/Mediawiki/Provider.php
src/Mediawiki/README.md
src/Mediawiki/composer.json

OAuth2 Provider for Mediawiki
https://www.mediawiki.org/wiki/OAuth/For_Developers#OAuth_2

Add Mediawiki Provider

---

monorepo-builder.yml
src/Blackboard/BlackboardExtendSocialite.php
src/Blackboard/Provider.php
src/Blackboard/README.md
src/Blackboard/composer.json

Blackboard OAuth Overview: https://docs.blackboard.com/rest-apis/learn/getting-started/3lo
Blackboard Developer API reference: https://developer.blackboard.com/portal/displayApi

Add Blackboard

---

monorepo-builder.yml
src/Exment/ExmentExtendSocialite.php
src/Exment/NotConfigExmentUrlException.php
src/Exment/Provider.php
src/Exment/README.md
src/Exment/composer.json

Exment is open source web database for managing information assets on the Web.  
For Web Database, SFA, CRM, Business improvement, ...  
Please read them.
<a href="https://github.com/exceedone/exment" target="_blank">GitHub</a>  
<a href="https://exment.net/docs/#/">Manual</a>  
<a href="https://exment.net/docs/#/api">How to config API</a>  
<a href="https://exment.net/reference/webapi.html">API Reference</a>

Append Exment Provider. 

---

monorepo-builder.yml
src/Bexio/BexioExtendSocialite.php
src/Bexio/Provider.php
src/Bexio/README.md
src/Bexio/composer.json

Bexio is a service for companies with it's own applications marketplace.
https://www.bexio.com/en-CH/
It would be good having it as a new socialite provider.

Added Bexio Provider

---

src/ConstantContact/Provider.php

ConstantContact have once again updated their endpoints:
https://v3.developer.constantcontact.com/api_guide/auth_update_apps.html

ConstantContact endpoint updates

---

src/Okta/Provider.php
src/Okta/README.md

See documentation here:
- https://developer.okta.com/docs/guides/revoke-tokens/main/
- https://developer.okta.com/docs/reference/api/oidc/#revoke
- https://developer.okta.com/docs/reference/api/oidc/#introspect

okta revoke and introspect functionality

---

monorepo-builder.yml
src/Starling/Provider.php
src/Starling/README.md
src/Starling/StarlingExtendSocialite.php
src/Starling/composer.json

This PR allows for Starling oAuth2 flow to be utilised. 
- Starling have particular endpoints for sandbox and have therefore followed similar spec in QuickBooks provider for determining which endpoint to utilise
- Also, they do not return the unique user ID as part of their identity call and it must be deduced by the token call. For now I have merged the two results and am in discussions with their technical team to see if there is a more accessible way of obtaining this information.
___
Website: https://www.starlingbank.com/
___
Docs: https://developer.starlingbank.com/docs

Add Starling Provider

---

.github/workflows/monorepo-split.yml
.github/workflows/subtree-pr-close.yml
.github/workflows/test.yml

This PR updates the actions versions

Update actions versions

---

monorepo-builder.yml
src/Toyhouse/Provider.php
src/Toyhouse/README.md
src/Toyhouse/ToyhouseExtendSocialite.php
src/Toyhouse/composer.json

Provider for https://toyhou.se/
Developer documentation: https://toyhou.se/~developer/oauth2
Thank you! :)

Add Toyhou.se provider

---

monorepo-builder.yml
src/AmoCRM/AmoCRMExtendSocialite.php
src/AmoCRM/Provider.php
src/AmoCRM/README.md
src/AmoCRM/composer.json

Hi, can I add one?
amoCRM: https://www.amocrm.com/
OAuth documentation: https://www.amocrm.com/developers/content/oauth/step-by-step/

add AmoCRM provider

---

src/LaravelPassport/Provider.php

To pass config to set Guzzle option
- https://github.com/laravel/socialite/issues/589
- https://github.com/laravel/socialite/blob/3342c75ca36228819b590482ed2a787a01f9a07e/src/SocialiteManager.php#L127

add 'guzzle' to custom Guzzle option

---

src/Apple/Provider.php
src/Apple/composer.json

v6 changelog:
https://github.com/firebase/php-jwt/releases/tag/v6.0.0

[Apple] Switch to firebase/php-jwt v6

---

src/Saml2/Provider.php

If the metadata provided by the IDP had multiple entity descriptors then this was not properly handled.
Fixes the issue described in #860. Props @robertdeboer.

Handle multiple entity descriptors in IdP metadata, by choosing the first one.

---

src/QQ/Provider.php

According to the description of the QQ documentation, it has been supported to return responses in json format.

feat: QQ provider OAuth 2.0 APIs already supports json format response

---

monorepo-builder.yml
src/PlanningCenter/PlanningCenterExtendSocialite.php
src/PlanningCenter/Provider.php
src/PlanningCenter/README.md
src/PlanningCenter/composer.json

This pull request implements a Socialite provider for [Planning Center](https://www.planningcenter.com/).
* [Planning Center's oAuth Docs](https://developer.planning.center/docs/#/overview/authentication)

Planning Center Provider

---

monorepo-builder.yml
src/Authentik/AuthentikExtendSocialite.php
src/Authentik/Provider.php
src/Authentik/README.md
src/Authentik/composer.json

Added a socialite provider for [Authentik](https://goauthentik.io/)
Base_URL is extracted to allow customisation to a specific Authentik instance

Added Socialite provider for Authentik

---

src/PlanningCenter/README.md

And I'm back again (sorry!). You can tell where I copied the `README.md` from

Change heading in Planning Center documentation

---

src/WeChatServiceAccount/Provider.php
src/WeChatWeb/Provider.php

This PR enforce strict `in_array` argument.

Enforce strict in_array argument

---

composer.json

Add composer.json support section and [normalize](https://github.com/ergebnis/composer-normalize) the file

Add composer.json support section and normalize the file

---

.github/workflows/normalize-composer.yml

Add a GA to normalize all composer.json files
This PR should be manually dispatched.

Add a GA to normalize all composer.json files

---

.github/workflows/pull-requests.yml

This PR ensures that a newly submitted PR have edit rights enabled for contributors.

Ensure that all submitted PRs have edit rights

---

tools/update-repo-descriptions.php

Ignore .github repository

---

src/Pr0gramm/Pr0AuthExtendSocialite.php
src/Pr0gramm/Provider.php
src/Pr0gramm/README.md
src/Pr0gramm/composer.json

Provider for german image board [Pr0gramm](https://pr0gramm.com/)
API-Docs: [Official Github Repo](https://github.com/pr0gramm-com/api-docs/blob/master/OAuth.md)
Currently configured for scope "user.name".

Add Pr0gramm provider

---

src/Patreon/Provider.php
src/Patreon/composer.json

Migrates from Patreon API v1 to v2. Fixes #890

Migrate from Patreon API v1 to v2.

---

monorepo-builder.yml
src/SubscribeStar/Provider.php
src/SubscribeStar/README.md
src/SubscribeStar/SubscribestarExtendSocialite.php
src/SubscribeStar/composer.json

Adde OAuth2 provider for [SubscribeStar](https://www.subscribestar.com/)
Docs: https://www.subscribestar.com/api

Added SubscribeStar provider 

---

src/Todoist/Provider.php

- Migrates the integration from passing the token by parameter (deprecated) to providing it via Auth Header

Fixes Todoist API Token Auth implementation

---

src/Saml2/InvalidSignatureException.php
src/Saml2/Provider.php
src/Saml2/README.md

This PR adds various SAML assertion validations including for timestamps, and repeated assertion IDs.

Add SAML validations

---

monorepo-builder.yml
src/Webflow/Provider.php
src/Webflow/README.md
src/Webflow/WebflowExtendSocialite.php
src/Webflow/composer.json

Provider for [Webflow](https://webflow.com/).
Developer docs: https://developers.webflow.com/docs/oauth

Add Webflow provider

---

monorepo-builder.yml
src/Onelogin/OneloginExtendSocialite.php
src/Onelogin/Provider.php
src/Onelogin/README.md
src/Onelogin/composer.json

Provider for [Onelogin](https://www.onelogin.com/).
Developer docs: https://developers.onelogin.com/openid-connect

Add new Onelogin Provider

---

src/Saml2/README.md

Saml2: Minor documentation update

---

src/Discord/Provider.php

https://github.com/discord/discord-api-docs/issues/264#issuecomment-505585425

feat: remove consent prompt on request

---

monorepo-builder.yml
src/Usos/Provider.php
src/Usos/README.md
src/Usos/Server.php
src/Usos/UsosExtendSocialite.php
src/Usos/composer.json

Provider for [USOS](https://usos.edu.pl). This is a polish universal university management system, which also allows students and teachers to log in via OAuth 1.0a to a third-party applications
Developer docs: https://apps.usos.edu.pl/developers/api/authorization/

Add USOS OAuth1.0a provider

---

src/Saml2/Provider.php
src/Saml2/README.md
src/Saml2/composer.json

[Saml2] Allow the administrator to choose an entity descriptor to use

---

src/Microsoft/Provider.php

Added ability to pull MS profile picture at the same time.
config keys:
* include_avatar = true
* include_avatar_size ? 648x648 as default

Added profile picture retrieval

---

src/Microsoft/README.md

Updated changes to reflect functionality added in PR #971

Docs update for PR #971

---

src/Apple/Provider.php

fix: added forward slash before Apple revoked url

---

src/StreamElements/Provider.php

fix: StreamElements scope separator

---

monorepo-builder.yml
src/LifeScienceLogin/LifeScienceLoginExtendSocialite.php
src/LifeScienceLogin/Provider.php
src/LifeScienceLogin/README.md
src/LifeScienceLogin/composer.json

This adds a new provider for [Life Science Login](https://lifescience-ri.eu/ls-login/) (from the European life science infrastructure).

Life Science Login provider

---

src/Apple/composer.json

Reverts SocialiteProviders/Providers#1006
See #1015

Revert "Add support for lcobucci/jwt 5.0"

---

src/Apple/Provider.php

As mentioned in https://github.com/SocialiteProviders/Providers/pull/1018#issuecomment-1535853166

Rid unnecessary override of getTokenField($code)

---

monorepo-builder.yml
src/Salesloft/Provider.php
src/Salesloft/README.md
src/Salesloft/SalesloftExtendSocialite.php
src/Salesloft/composer.json

It creates the Socialite provider for [Salesloft](https://developers.salesloft.com/)

feat: create Salesloft provider

---

.gitignore

This PR also ignores the `vendor` in `src` directory

Also ignore the `vendor` in `src` directory

---

.github/workflows/monorepo-split.yml
.github/workflows/normalize-composer.yml
.github/workflows/subtree-pr-close.yml
.github/workflows/test.yml

Use PHP 8.2 for GitHub Actions
Also run tests for PHP 8.2

Also use PHP 8.2 for GA

---

src/AutodeskAPS/Provider.php
src/VKontakte/Provider.php

This PR removes useless properties, which values have not been overridden.

Remove useless properties

---

src/FusionAuth/Provider.php

fix: fusionauth undefined key exception

---

src/ArcGIS/Provider.php
src/AzureADB2C/Provider.php
src/Jira/Server.php
src/LaravelPassport/Provider.php
src/Mattermost/Provider.php
src/OpenStreetMap/Provider.php
src/Trello/Server.php
src/Usos/Server.php
src/Wave/Provider.php

This PR removes lots of redundant arguments

Remove redundant arguments

---

src/Azure/Provider.php
src/Bitrix24/Provider.php
src/ConstantContact/Provider.php
src/GovBR/Provider.php
src/Instagram/Provider.php
src/LifeScienceLogin/Provider.php
src/Neto/Provider.php
src/Onelogin/Provider.php
src/OpenStreetMap/Provider.php
src/PayPal/Provider.php
src/Wave/Provider.php
src/Worldcoin/Provider.php

Always ensure that the body response is cast as string

Always ensure that the body response is cast as string

---

src/Etsy/composer.json
src/FusionAuth/composer.json
src/Patreon/composer.json
src/Pr0gramm/composer.json
src/Subscribestar/composer.json
src/SuperOffice/composer.json
src/Vatsim/composer.json
src/Wave/composer.json
src/Webflow/composer.json

This PR normalizes some dependencies
(so that Laravel 10.x can be supported by all packages)

Normalize dependencies 

---

src/LifeScienceLogin/README.md

I was asked to add funding information to the readme of my Life Science Login provider. Please merge my updated version of the readme.

Update Life Science Login readme

---

src/Adobe/AdobeExtendSocialite.php
src/AutodeskAPS/AutodeskAPSExtendSocialite.php
src/Gumroad/GumroadExtendSocialite.php
src/Monzo/MonzoExtendSocialite.php
src/MusicBrainz/MusicBrainzExtendSocialite.php
src/Salesloft/SalesloftExtendSocialite.php
src/Saml2/Saml2ExtendSocialite.php
src/Usos/UsosExtendSocialite.php

This PR normalizes declarations and docblocks

Normalize declarations and docblocks

---

src/AutodeskAPS/composer.json
src/Salesloft/composer.json

This PR enforces consistant spacing in json files

Enforce consistant spacing in json files

---

src/Flexkids/Provider.php
src/Jira/RsaSha1Signature.php
src/Weibo/Provider.php
src/Withings/Server.php

Fix docblocks

---

src/Apple/composer.json
src/Eveonline/composer.json
src/Xero/Provider.php
src/Xero/composer.json

This PR bumps the `firebase/php-jwt` version to `^6.8`

Bump firebase/php-jwt version to ^6.8

---

src/TikTok/Provider.php
src/TikTok/README.md

I have added a parameter which gives you the unique username on the platform of each user and assigned it to the nickname.

[5.x.x] Update Tiktok Provider.php

---

src/Microsoft/README.md

Update Microsoft README.md with details about retrieving a refresh token

Update Microsoft README.md

---

src/Slack/Provider.php

See https://github.com/laravel/socialite/issues/681

fix: slack bot provider

---

src/Azure/README.md

The values that can be put in the client_id to create a valid URL are from this article:  https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50020-user-account-identity-provider-does-not-exist#solution-use-the-correct-sign-in-url

Update to README.md regarding non-single tenant apps

---

.github/workflows/monorepo-split.yml
.github/workflows/normalize-composer.yml
.github/workflows/subtree-pr-close.yml
.github/workflows/test.yml

Also run tests for PHP 8.3

---

monorepo-builder.yml
src/JumpCloud/JumpCloudExtendSocialite.php
src/JumpCloud/Provider.php
src/JumpCloud/README.md
src/JumpCloud/composer.json

Provider for jumpcloud.com. 
JumpCloud provides SSO for free for small teams (<= 10). 
It was successfully integrated and tested on https://gitalert.com/
Docs:
https://jumpcloud.com/support/sso-with-oidc

Add JumpCloud Provider

---

src/MakerLog/Provider.php
src/Vercel/Provider.php

This PR normalizes the case of the identifiers names

Normalize the case of the identifiers names

---

src/DocuSign/DocuSignExtendSocialite.php
src/Indeed/IndeedExtendSocialite.php
src/StartGg/StartGgExtendSocialite.php

This PR removes useless comments

Remove useless comments

---

src/Microsoft/Provider.php

> Trying to access array offset on value of type null

Microsoft | Fix potential array access error

---

src/Azure/Provider.php

Add support for optional post_logout_redirect_uri

---

src/WeChatServiceAccount/README.md
src/WeChatWeb/README.md
src/WeixinWeb/README.md

For:
https://github.com/SocialiteProviders/website/issues/50

Fix wrong composer package name.

---

monorepo-builder.yml
src/Fiken/FikenExtendSocialite.php
src/Fiken/Provider.php
src/Fiken/README.md
src/Fiken/composer.json

Fiken.no is a Norwegian online accounting system.

feat: fiken provider

---

src/HubSpot/Provider.php

Add refreshToken method for Hubspot
Inspire by:
https://github.com/SocialiteProviders/Apple/blob/master/Provider.php#L289-L299

Add refreshToken for HubSpot

---

monorepo-builder.yml
src/Zettle/Provider.php
src/Zettle/README.md
src/Zettle/ZettleExtendSocialite.php
src/Zettle/composer.json

Zettle by Paypal is a point of sale payment provider.

feat: zettle provider

---

src/Microsoft/Provider.php

#1223 Add department to the list of fields returned in the microsoft provider

---

src/Microsoft/Provider.php

#1233 Add employeeId to the list of fields retrieved for Microsoft provider

---

monorepo-builder.yml
src/EduID/EduIDExtendSocialite.php
src/EduID/Provider.php
src/EduID/README.md
src/EduID/composer.json

Documentation is avaiable here: https://help.switch.ch/eduid/docs/services/start/
Technical overview of endpoints is avaiable here: https://login.eduid.ch/.well-known/openid-configuration
PR for the website documentation: https://github.com/SocialiteProviders/website/pull/58

Added EduID provider

---

src/YNAB/Provider.php

One more, didn't get the token URL right.

Fix token url for YNAB provider

---

src/Zitadel/Provider.php

This PR fix the `zitadel` provider.

Fix `zitadel` provider

---

composer.json
src/AutodeskAPS/composer.json
src/AzureADB2C/composer.json
src/Dataporten/composer.json
src/EduID/composer.json
src/Etsy/composer.json
src/GovBR/composer.json
src/Ivao/composer.json
src/JumpCloud/composer.json
src/Linode/composer.json
src/Mediawiki/composer.json
src/Monday/composer.json
src/Onelogin/composer.json
src/OpenStreetMap/composer.json
src/Roblox/composer.json
src/Smashcast/composer.json
src/Steam/composer.json
src/Subscribestar/composer.json
src/Teamleader/composer.json
src/Threads/composer.json
src/UCL/composer.json
src/Usos/composer.json
src/Vatsim/composer.json
src/Wave/composer.json
src/YNAB/composer.json
src/Zettle/composer.json
src/Zitadel/composer.json

Normalize (and fix) all `composer.json` files

Normalize all composer.json files

---

src/Line/Provider.php
src/Line/README.md

According to the official documentation, add the bot_prompt configuration.
https://developers.line.biz/en/docs/line-login/link-a-bot/#redirect-users

LINE - Add bot_prompt config supported

---

monorepo-builder.yml
src/ClickUp/ClickUpExtendSocialite.php
src/ClickUp/Provider.php
src/ClickUp/README.md
src/ClickUp/composer.json

This PR adds [ClickUp](https://clickup.com/) Provider
[ClickUp OAuth2 Doc](https://clickup.com/api/developer-portal/authentication#oauth-flow)

Add ClickUp provider

---

src/Calendly/Provider.php

This PR fix the Calendly provider

Fix Calendly provider

---

src/HubSpot/Provider.php

This PR fix `Hubspot` provider

Fix `Hubspot` provider

---

src/Acclaim/Provider.php
src/Bitrix24/Provider.php
src/Clover/Provider.php
src/Harvest/Provider.php
src/HeadHunter/Provider.php
src/LaravelPassport/Provider.php
src/Monzo/Provider.php
src/Netlify/Provider.php
src/OSChina/Provider.php
src/Redbooth/Provider.php
src/SharePoint/Provider.php
src/Slack/Provider.php
src/Trakt/Provider.php
src/TwitCasting/Provider.php
src/UFS/Provider.php
src/Venmo/Provider.php
src/Zalo/Provider.php

This PR removes some useless scopes

Remove useless scopes

---

src/Clover/Provider.php
src/DocuSign/Provider.php
src/Indeed/Provider.php
src/LifeScienceLogin/Provider.php
src/Salesloft/Provider.php
src/Slack/Provider.php
src/VKontakte/Provider.php
src/Zitadel/Provider.php

This PR ensures the response body is always casted as string

Ensure the response body is always casted as string

---

src/Clover/Provider.php
src/Etsy/Provider.php
src/GovBR/Provider.php
src/Instagram/Provider.php
src/LifeScienceLogin/Provider.php
src/Onelogin/Provider.php
src/Pr0gramm/Provider.php
src/Steam/Provider.php
src/Subscribestar/Provider.php
src/Usos/Provider.php
src/Wave/Provider.php
src/Webflow/Provider.php
src/Worldcoin/Provider.php

This PR normalize the provider identifiers

Normalize the provider identifiers

---

src/ClickUp/Provider.php
src/Line/Provider.php

Run pint on the codebase and fix the code style

Fix code style

---

pint.json
src/Zitadel/Provider.php

Add `array_push` rules to pint

Add `array_push` rules to pint

---

src/Clerk/ClerkExtendSocialite.php
src/Fiken/FikenExtendSocialite.php
src/StartGg/StartGgExtendSocialite.php
src/Zettle/ZettleExtendSocialite.php
src/Zitadel/ZitadelExtendSocialite.php

Normalize all `handle` methods

Normalize all `handle` methods

---

src/PayPalSandbox/README.md

It was `socialiteproviders/paypalsandbox` but original package is `socialiteproviders/paypal-sandbox`. so i changed this.

package name fix

---

monorepo-builder.yml
src/Nuvemshop/NuvemshopExtendSocialite.php
src/Nuvemshop/Provider.php
src/Nuvemshop/README.md
src/Nuvemshop/composer.json

Very similar to existent MercadoLibre but it changes the auth URL.
Docs: https://tiendanube.github.io/api-documentation/authentication

Add Nuvemshop Custom Provider

---

composer.json

Add Laravel pint to dev dependencies

Add Laravel pint to dev dependencies

---

src/MakerLog/Provider.php
src/Meetup/Provider.php
src/Nextcloud/Provider.php
src/StackExchange/Provider.php
src/TeamService/Provider.php
src/Vercel/Provider.php
src/Webex/Provider.php
src/Whmcs/Provider.php

Use `RequestOptions::QUERY` when possible

Use `RequestOptions::QUERY` when possible

---

src/Shopify/Provider.php

[Shopify are deprecating their REST API and moving to GraphQL by February of next year.](https://shopify.dev/docs/apps/build/graphql/migrate/new-product-model)
This update will ensure functionality is not impacted when the REST API is turned off.

Shopify - REST API deprecation - Move to GraphQL endpoint

---

src/Fiken/Provider.php
src/LifeScienceLogin/Provider.php

This PR inlines some useless variables

Inline variables

---

.github/workflows/monorepo-split.yml
.github/workflows/normalize-composer.yml
.github/workflows/subtree-pr-close.yml
.github/workflows/test.yml

This PR introduces for PHP 8.4 support

PHP 8.4 support

---

src/AutodeskAPS/Provider.php
src/LaravelPassport/Provider.php
src/Minecraft/Provider.php
src/SuperOffice/Provider.php

This PR removes some useless casts.

Remove useless casts

---

src/Klarna/Provider.php
src/Nuvemshop/Provider.php

This PR removes a few useless docblocks.

Remove a few useless docblocks

---

monorepo-builder.yml
src/Kinde/KindeExtendSocialite.php
src/Kinde/Provider.php
src/Kinde/README.md
src/Kinde/composer.json

Add Provider for https://kinde.com/

feat: Add Kinde provider

---

monorepo-builder.yml
src/PropelAuth/PropelAuthExtendSocialite.php
src/PropelAuth/Provider.php
src/PropelAuth/README.md
src/PropelAuth/composer.json

Add [PropelAuth](https://www.propelauth.com/) provider

Add propelauth provider

---

src/HabrCareer/Provider.php
src/Minecraft/Provider.php
src/Saml2/Provider.php

use stateless property when possible

use stateless property when possible

---

src/Saml2/Provider.php

Simplify condition, no need to use `strlen`

Simplify condition

---

.github/workflows/coding-standards.yml
.github/workflows/monorepo-split.yml

Update `coding-standards` workflow:
- Use `php 8.4`
- Update the action versions
- Install pint using `shivammathur/setup-php`

Update the `coding-standards` workflow

---

src/AzureADB2C/Provider.php
src/Microsoft/Provider.php

Use clientId property instead of trying to access it via the config array.

Use clientId property

---

src/GoHighLevel/Provider.php

- add missing bearer token
- merge auth data from creds response into user data.

fix: high level auth/token changes

---

src/LifeScienceLogin/Provider.php

Hard-coding the URLs eliminates possible errors from caching the config JSON.

Make Life Science Login less error-prone

---

monorepo-builder.yml
src/NFDILogin/NfdiLoginExtendSocialite.php
src/NFDILogin/Provider.php
src/NFDILogin/README.md
src/NFDILogin/composer.json

This is the authentication method for the German national research data infrastructure.
See: https://nfdi-aai.de/

Add NFDI Login provider

---

monorepo-builder.yml
src/Didit/DiditExtendSocialite.php
src/Didit/Provider.php
src/Didit/README.md
src/Didit/composer.json

Docs: https://docs.didit.me/auth-and-data/sign-in-api-reference/full-flow

feat: Add Didit provider

---

src/Etsy/README.md

Added updated Laravel 11+ instructions

Update README.md for Laravel 11+ support
